### ISSUE TITLE
Child element shows [object object] page due to nested lit-element path

### ISSUE THREAD

**Issue by mahdiridho** [Polymer/lit-element#1005]
## Description
We have several local lit-element based libraries to be installed on many projects. We have done this approach since polymer v3 to collect our internal reusable elements.

It has been long issue since polymer v3 where we need to be struggling with duplicate or nested libraries. On polymer v3, we solved this issue with several solution such as custom script for pre-install, deduping-fix and npm dedupe

## Old followed issue
https://github.com/Polymer/polymer-starter-kit/issues/1123

## Expectation
We migrated to lit-element to improve our development and find new spirit. One thing of our expectations was hopefully the duplication issue will be gone. So it will make simplify the development.

However, We still need npm dedupe every succeed install the packages. If possible - as we integrate lit-element We want to move away from dedupe

## Demo
Kindly to check our demo link here and follow the readme to serve :

[litelementInheritance](https://github.com/flatmax/litelementInheritance)

On the master branch, it works by npm dedupe
On the case branch, we will see [object object] on the browser page

We tried several solutios on the branches idea/one, idea/two, idea/three. However, we think they are bad idea. Any good ideas?

**Comment by flatmax** [comment]
We are having trouble rendering inherited classes. The only thing rendered is "[object Object]" when node_modules has nested files.

This repo demonstrates the problem : [litelementInheritance](https://github.com/flatmax/litelementInheritance).

To fix the problem we need to run npm dedupe, the only difference between the working example and the not working example is the structure of the node_modules directory. The code is the same.

The structure of the code is like so :

```
export class ParentElement extends LitElement {
  render(){     return html` ${this.name} `;   }
}

export class ChildElement extends ParentElement {
  render(){    return html`  ${super.render()}   `;   }
}

```

Any ideas on how to avoid using npm dedupe to fix this problem ?

**Comment by sorvell** [comment]
Using `npm dedupe` is a good way to address this issue. Can you explain why you want to avoid using `npm dedupe`?

**Comment by flatmax** [comment]
Using npm dedupe once would require every project to use npm dedupe. Otherwise dependencies would disappear during development of other projects/elements.

For example, project1/child1-element extends hq/parent-element. project2/child2-element extends hq/parent-element.
Project1 does npm install, then develops. All good, all of parent-element's dependencies are in node_modules/parent-element.
Project2 does npm install, npm dedupe, then develops. All good, all dependencies are now in Project2/node_modules
Project1 refreshes in the browser and now it can't find parent-element.

Are there other approaches people generally use to get around these element moving probelms posed  by dedupe  ?

**Comment by justinfagnani** [comment]
`npm dedupe` in Project 1 should not affect Project 2, unless I'm misunderstanding your setup. `dedupe` doesn't do anything that `npm i` couldn't have done on initial install anyway. The end result of both is a valid, semver-compatible, node_modules/ directory.

**Comment by justinfagnani** [comment]
Closing this as a duplication of https://github.com/Polymer/lit-html/issues/320

Because of `instanceof`, we need libraries that share lit-html template results and directives to use the same instance of the lit-html library. This is pretty fundamental unless and until we replace `instanceof` with some kind of branding tag, and make sure that works across potential incompatble major versions of lit-html

**Comment by flatmax** [comment]
The setup uses npm link.
I think you are indicating that to remove the npm dedupe requirement would be too difficult.
