### ISSUE TITLE
Accurate typings for property and internalProperty decorators

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [Polymer/lit-element#1009]
## Description

Recently, a new `internalProperty` decorator was added with the following intent.
```js
 * This (property) decorator should only be used for public fields. Private or protected
 * fields should use the [[`internalProperty`]] decorator.
```

The problem is that the typings of both `property` and `internalProperty` decorators are very loose and match any property, be it public, protected or private.

I propose to make the typings more accurate so that `property` can only be applied to public properties and `internalProperty` can only be applied to protected or private properties.

## Acceptance criteria

The typings for the `property` decorators are easy to implement, since `keyof` will provide all public properties of a class. Currently, there is no way to obtain the protected and private properties.  However if [typescript merged support for negated types](https://github.com/microsoft/TypeScript/pull/29317), we would be able to workaround this limitation and provide accurate typings for `internalProperty`.

I propose to merge first the typings for `property` decorator, and postpone `internalProperty` typings until it becomes feasible.

**Comment by sorvell** [comment]
Thanks for the suggestion and the PR. While we basically agree with the proposed change, the concern is that it would be a breaking change. We've observed using `@property` on protected/private properties. There are some use cases for this (something that should only be considered by attribute but needs to be reflected into a private property), but it should definitely be uncommon.

We've elected not to change this right now since it would be breaking, but we're going to label the issue as something we're going to consider changing in the next major version.
