### ISSUE TITLE
[docs] Polymer features that aren't in LitElement

### ISSUE THREAD

**Issue by rictic** [Polymer/lit-element#101]
It looks like observers and computed functions are not supported (AIU https://github.com/Polymer/lit-element/issues/30#issuecomment-385568414), and instead you just do some logic in either didRender or _render, which is reasonable enough, but it'd be nice for it to be documented.

I started with the decorators linked here: https://github.com/Polymer/lit-element/issues/7#issuecomment-395878088 and their typings mention observer and computed.

**Comment by PaulHMason** [comment]
Observers and computed functions aren't a feature of lit-element because they aren't required, so it doesn't really make sense to document that fact. The confusion stems from people comparing lit-element to a Polymer element, but they really aren't related and drawing comparisons will probably make things more confusing (especially to people who aren't familiar with Polymer).

**Comment by akc42** [comment]
Yes, I just wasted a day chasing down the fact that camelcase propertied don't map to properties in the template with a "-" in them.  Event though this was a lit element sitting inside a polymer 3 template

https://github.com/Polymer/lit-element/issues/128

**Comment by ernsheong** [comment]
`query` and `queryAll` decorators are also undocumented

**Comment by katejeffreys** [comment]
Duplicate of https://github.com/Polymer/lit-element/issues/63

**Comment by katejeffreys** [comment]
Duplicate of #63
