### ISSUE TITLE
Inheriting styles?

### ISSUE THREAD

**Issue by tamis-laan** [Polymer/lit-element#1020]
I'm trying to create my own custom input element which wraps a regular <input> element:
```javascript 
  render() {
    return html`
      <input value=${this.value}    @focusin=${this.focusIn}
                                    @focusout=${this.focusOut}
                                    @input=${this.onInput}
                                    ?required=${this.required}
      ></input>
    `
```
Now I need to pass on the style from the component  itself to the <input> element. As far as I understand this should be done with the all:inherit method as so:
```javascript
static get styles() {
  return [css`
      input {all:inherit !important;}
      input:valid {all:inherit !important;}
      input:focus {border-color:inherit !important;}
  `]
```
This however is not working, and I'm not sure why.

**Comment by Westbrook** [comment]
Interesting approach! You do have some options here, but would open lots of edge case issue, IMO. Check this out: https://stackblitz.com/edit/jzmw1p?file=my-element.js Hover, etc. styling gets passed, sort of...

With your `input {all:inherit !important;}` the `appearance: input;` style rules are lost, which causes some issues with getting "default" input styling. If you use `:host { display: content; }` with mixed levels of support, you'd be able to set values _on_ the root element that were passed (without being duplicated) to the `<input>` inside of them.

Looking forward to hear more on what you find here!

**Comment by tamis-laan** [comment]
Ah so I'm not making any mistakes, however in my code for some reason these pseudo states `input:valid` and `input:focus` are not being inherited only the base state `input` is inherited from outside the component. And I can't figure out why? Maybe I'm running up an old bug?

**Comment by kevinpschaaf** [comment]
For allowing users to select the native `:focus` and `:valid` pseudo-selectors on your custom element, you'll need help from the browser forwarding those states to the CSS engine.  Fortunately, those features now have spec'ed proposals and are shipping in Chrome. Unfortunately, they're not shipped elsewhere yet and are not polyfilled.

I've updated your example here using the new "[Form associated custom elements](https://www.chromestatus.com/feature/4708990554472448)" and [delegatesFocus](https://github.com/TakayoshiKochi/tabindex-focus-navigation-explainer/blob/master/TabindexFocusNavigationExplainer.md#delegatesfocus-details) features. This should work natively in Chrome: 

https://stackblitz.com/edit/jzmw1p-8vbe9t?file=my-element.js

For other browsers, it won't be possible yet to use the native CSS `:focus`/`:valid` pseudo-selectors since there's no way to tell the CSS engine on those browsers that those states are active on the element.  The next best thing would likely be to write code to toggle attributes on the host element in response to focus/validity events on the `input` element, and have users select against those attributes instead, e.g. `my-element[focus] { /* focused state */ }`.

I'll go ahead and close this issue since I believe this is the best answer we can provide at this point, also noting that this is a native browser behavior question, not one strictly related to `LitElement`, but happy to help!

**Comment by tamis-laan** [comment]
thnx using the second route it works on all browsers! Although super ugly :#
