### ISSUE TITLE
how to set the default values of a  prototype??

### ISSUE THREAD

**Issue by hzmnet** [Polymer/lit-element#1040]
how to solve somehow we want to get values from an element prototype?
when we get value from "litelemnt.prototype.accessKey" the browser gets an error and stops running the code.

## Description
- Who wants the functionality
- What it is they want
- Why they want it
- Functional description of task/subtask

## Acceptance criteria
What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.

**Comment by LarsDenBakker** [comment]
Do you have more information about what you're trying to do? A code example which shows the error?

A lit element is a regular javascript class, it doesn't change how values can be accessed from javascript.

**Comment by justinfagnani** [comment]
Yes, we definitely need more information here. I don't know what `litelemnt.prototype.accessKey` refers to.

**Comment by hzmnet** [comment]
I need to store a list of element prototypes. and then according to the default property value "type" which value default is "form", "list", etc, to do some logic codes.

**Comment by justinfagnani** [comment]
Do you have some example code?

**Comment by hzmnet** [comment]
@justinfagnani  like this example    https://stackblitz.com/edit/lit-element-example-m49smv

**Comment by sorvell** [comment]
There are a couple of issues here. First, setting `value` as you've done in the example above is not supported in LitElement. Instead you need to initialize the value in the constructor or use a class field and the `@property` decorator. As the default value is typically set on the instance, it's not available via the prototype. Generally accessing a default value via the prototype like this is not safe but you can setup classes that make this safe if you want to use this pattern. It seems better, however, to expose this type of property metadata directly on the constructor rather than try to inspect the prototype.

However, just to show that something like this is possible, [here's an example](https://stackblitz.com/edit/lit-element-example-uvsfkr?file=index.js). The example uses LitElement's ability to customize property accessors via `getPropertyDescriptor` to add the ability to set a `defaultValue` via the property options (and it does this in a way that's safe to access via the prototype as you want). Note, that it's important to define the custom elements as LitElement actually creates the property accessors when the custom element is defined.

Hope that helps show some of the flexibility that's possible.

**Comment by hzmnet** [comment]
thank you for your detailed information! It's really a big help for me! thank you all!
