### ISSUE TITLE
LitElement SVG children as slot

### ISSUE THREAD

**Issue by reutopiaer** [Polymer/lit-element#1042]
https://stackoverflow.com/questions/54752369/litelement-svg-children-as-slot

#### Live Demo

https://stackblitz.com/edit/wy6bhj?file=index.html

#### Steps to Reproduce
``` html
<svg><slot></slot></svg>
```

#### Expected Results

``` html
<svg><rect width="100%" height="100%" fill="red" /></svg>
```
#### Actual Results
``` html
<svg><slot></slot></svg>
```

**Comment by sorvell** [comment]
As noted in the stack overflow, passing svg content via a slot is not supported in Shadow DOM. Here's an [example without LitElement](https://jsbin.com/ziyahir/edit?html,output).

Instead, you would need to slot the entire <svg> as is shown in the link above.

Closing since this is not a LitElement specific issue. If you'd like to address improving the core platform functionality, we recommend filing a Chrome bug or spec issue.
