### ISSUE TITLE
Property decorator doesn't trigger render

### ISSUE THREAD

**Issue by u-can-do-it** [Polymer/lit-element#1052]
### Description
Property update doesn't trigger render.

#### Live Demo

https://codesandbox.io/s/react-typescript-forked-uohq1?file=/src/index.tsx

#### Steps to Reproduce
Click + or - button
p- button has static get properties and @property decorator and update works.
t-button has only @property decorator so re render doesn't works.

### Browsers Affected

- [x] Chrome
- [x] Brave
- [x] Chromium
- [x] Firefox

### Versions

- lit-element: 2.3.1

**Comment by u-can-do-it** [comment]
#

**Comment by sorvell** [comment]
You've hit a known issue around decorating class fields. The spec for class fields was recently changed so that they are defined on the object instance rather than just being set. This will mask an accessor installed on the object prototype as `@property` does. Some transpilers have been updated to support this and you'll see this problem when using class fields with those transpilers. TypeScript works fine, but it looks like this code editor is using Babel with a setting to define class fields. We'll need to investigate if there's a better setup to use with Babel.

We're trying to consider a good fix for this in general. Eventually platform supported decorators should address this use case. In the meantime, since the decorators spec is highly in flux, we're not in a great spot.

Although it's annoying, I'd recommend avoiding use of class fields (specifically setting the property and not just declaring it) + decorators until this is worked out.

There is a workaround, but it imposes a small performance penalty on the element, so I wouldn't really recommend this. It also requires calling a private function for what it's worth:

https://codesandbox.io/s/react-typescript-forked-u7itz?file=/src/t-btn.ts:519-657

```
constructor() {
    super();
    (this as any)._saveInstanceProperties();
  }
```

The performance concern comes from the fact that this leverages functionality that was intended to support lazy loading element definitions (something that is occasionally done for specific instances of a component) for all instances of a given component.

**Comment by justinfagnani** [comment]
I don't think `_saveInstanceProperties` is the way to go here because of the shape changes it'll incur on each instance.

There should be a way to turn off define semantics for class fields. In tsconfig.json that's done with

```json
    "useDefineForClassFields": false,
```

And in Babel is should be done with:

```json
{
  "plugins": [
    ["transform-class-properties", { "spec": false }]
  ]
}
```

I'm not familiar with create-react-app or this TS-based fork. For some reason changing the tsconfig doesn't fix the issue, and I don't see a .babelrc.json.

@u-can-do-it do you know how to change the Babel config for your project?

**Comment by bennypowers** [comment]
are there plans to support spec-aligned uses?

typescript is eventually going to set `useDefineForClassFields: true` by default, to align with browser behaviour. Typescript already errors if you try to override a class field with accessors, for instance

**Comment by u-can-do-it** [comment]
> I don't think `_saveInstanceProperties` is the way to go here because of the shape changes it'll incur on each instance.
> 
> There should be a way to turn off define semantics for class fields. In tsconfig.json that's done with
> 
> ```json
>     "useDefineForClassFields": false,
> ```
> 
> And in Babel is should be done with:
> 
> ```json
> {
>   "plugins": [
>     ["transform-class-properties", { "spec": false }]
>   ]
> }
> ```
> 
> I'm not familiar with create-react-app or this TS-based fork. For some reason changing the tsconfig doesn't fix the issue, and I don't see a .babelrc.json.
> 
> @u-can-do-it do you know how to change the Babel config for your project?

Thank You for the response. I tried both but didn't work. I removed all decorators and declared components in the old way.

**Comment by justinfagnani** [comment]
@bennypowers 

> are there plans to support spec-aligned uses?
> 
> typescript is eventually going to set useDefineForClassFields: true by default, to align with browser behaviour. Typescript already errors if you try to override a class field with accessors, for instance

I assume that TypeScript can't enable useDefineForClassFields by default without fixing this issue.
