### ISSUE TITLE
on click event of button want to toggle dropdown

### ISSUE THREAD

**Issue by anjneeksharma** [Polymer/lit-element#1091]
If user click on button on click events its calling one function that function should toggle drop down
but I am using    let drop = document.querySelector(".classname");  but this statement is returning me null instead of that drop down.

is someone can help me how can i update dropdown based on it class 

 toggleDropdown(e) {
      let abc = document.querySelector(".newclass");
      console.log(abc);
    }

**Comment by sorvell** [comment]
The description is a little unclear and it would be helpful to have a reproduction of the issue. However, maybe it's possible that you're trying to use `document.querySelector` to try to find an element that's in your element's shadowRoot? If so, you'd need to do `this.shadowRoot.querySelector` instead of `document.querySelector`.

**Comment by sorvell** [comment]
Closing based on previous answer. Please feel free to re-open if the problem persists.
