### ISSUE TITLE
Trigger event after component is connected and rendered?

### ISSUE THREAD

**Issue by tamis-laan** [Polymer/lit-element#1145]
I would like to trigger a function once my component is added to the DOM and completely rendered. How can I achieve this using lit-element?

Right now I set a timeout of 200 ms within ConnectedCallback and call my function. I also use await updateComplete as I thought this ment waiting until the render process completes. 

```javascript
  async connectedCallback() {
    super.connectedCallback()
    await this.updateComplete;
    // Apply scalling
    setTimeout(_=>{this.scaling()},200)
  }
```

**Comment by sorvell** [comment]
The component is completely rendered when the `updateComplete` promise resolves. You should not need the `setTimeout`.

**Comment by tamis-laan** [comment]
> The component is completely rendered when the `updateComplete` promise resolves. You should not need the `setTimeout`.

Does that include the sub-components contained in the `<slot></slot>` ? 

My function `this.scalling()` checks the height of my component in pixels and then adds a `transform: scale(...)` to the styling of the component. However the height in pixels is wrong hence the timeOut to make sure the component is completely drawn.

**Comment by sorvell** [comment]
No, it does not. For children in your shadowRoot, you can implement `_getUpdateComplete()` to await any specific elements you care about. However, this is probably not great for slotted content. Rather than use `setTimeout`, it's better to use `requestAnimationFrame` which should be sufficient.

```js
async connectedCallback() {
  super.connectedCallback()
  await new Promise((resolve) => requestAnimationFrame(resolve));
  this.scaling()
}
```

Hope that helps. Feel free to re-open if more info is needed.

**Comment by tamis-laan** [comment]
It did not solve my issue, but if I combine it with a setTimeout of 0 ms It does work:
``` javascript
async connectedCallback() {
  super.connectedCallback()
  await new Promise((resolve) => requestAnimationFrame(resolve));
  setTimeout(_=>{this.scaling()},0)
}
```
I found the`setTimeout(_=>{this.scaling()},0)` hack somewhere else, which doesn't work on it's own, only with your proposed solution.

**Comment by user1207504** [comment]
You can implement firstUpdated() to help in this scenario. This is executed only once in the lifecycle and after the first render.

**Comment by justinfagnani** [comment]
Generally, unless some scheduling is customized, `firstUpdated()` should be called before the requestAnimationFrame after connectedCallback.

In this case if you're trying to respond to the size of the element, I'd use ResizeObserver so that it happens dynamically any time the size changes.

Otherwise, it'd be good in any particular case to debug and see what order connected/rAF/paint is done in (it should be that order), and see what else is effecting the size, but I know that a lot of times with async issues, people try to just be "more async". In that case you could wait an setTimeout(0). If that isn't working and you have to go back to setTimeout(200), then there's something really late happening that's messing with the size like a font or CSS loading, and then ResizeObserver is the only robust way to handle it.
