### ISSUE TITLE
'title' and other global HTML attributes aren't picked up by LitElement's properties

### ISSUE THREAD

**Issue by Alber70g** [Polymer/lit-element#133]
### Description

When using an element with `title` or other global HTML attributes (https://www.w3schools.com/tags/ref_standardattributes.asp) they aren't picked up by LitElement.

#### Live Demo

Example when using `title` and `thetitle`: https://stackblitz.com/edit/lit-element-example-v5qcss?file=index.js

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by pshihn** [comment]
I'm assuming this is because 'title' is a built in attribute (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/title) which provides a tooltip like behavior. In your example, if you hover of the empty quote span, you will see the 'The Title' as a tooltip. 
It's always confusing when a property is overloaded like that. Perhaps use a different property name?

**Comment by pshihn** [comment]
Overriding built-in attributes like 'title' is always tricky because you're overloading the meaning of it. 
If you want to get the 'title' (as in the tooltip) from inside the element, you can always just get it from `this.title` since your custom element extends HTMLElement. 
If you are actually not planning to use title as a tooltip but as text in your component, then I suggest using a different property name to avoid confusion.

**Comment by sorvell** [comment]
You actually will be able to do this in the next version `0.6` (currently available as `dev`) for at least some native attributes. Your mileage may vary, but it does look like at least these cases will work ok. You will need to ensure that you set `reflect: true` to maintain the native behavior for these attributes.

Here's an example: http://jsbin.com/zoreluy/edit?html,output.
