### ISSUE TITLE
Lifecycle method updated() gets called before element with <slot> has completed render

### ISSUE THREAD

**Issue by gitaarik** [Polymer/lit-element#219]
### Description
When you use a child element with slotted content, that element is not yet rendered on the first call to the `updated()` lifecycle method of the parent element. This is problematic when you want to do post-rendering DOM manipulation, because the DOM is not yet in it's final state, so the width of a certain element for example is not yet finalized.

#### Live Demo
Demo: https://awesome-jet-1.glitch.me/
Source: https://glitch.com/edit/#!/awesome-jet-1?path=index.html

There's an `alert()` in the `updated()` method, then you see that the `SlotElement` hasn't been rendered yet the first time, and the width of `#my-div` is the width of the page in Firefox and `0` in Chrome. Then after the initial render when you increase the counter, you see the next time in the `alert()` that the width is 400px.

#### Steps to Reproduce
1. Create a custom element with a `<slot></slot>`
2. Set some styling in this element so you can see when it gets rendered
3. Use this element in a parent element
4. In the parent element, put an `alert()` in the `updated()` lifecycle method
5. See that on the first render, the styling of the child element is not yet rendered

#### Expected Results
You would assume that everything in the element has been rendered when the `updated()` lifecycle method is called.

#### Actual Results
The template of the element width `<slot></slot>` is not rendered when `updated()` is called the first time.

### Browsers Affected
- [x] Chrome
- [x] Firefox

### Versions
- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by sorvell** [comment]
In general, when a LitElement (`host`) renders another LitElement (`client`), the `host` is updated *before* the `client`. When a `host` needs to wait for a `client` to update, it can get the element and wait for the `updateComplete` promise to resolve before taking action.

For tasks like measuring, however, it's typically best to do this in a `requestAnimationFrame`. Since updates are always processed via microtasks, they are always completed before a `requestAnimationFrame` (a task) callback is called.

Here's an updated example: https://glitch.com/edit/#!/berry-marten?path=index.html:62:46

**Comment by gitaarik** [comment]
Aha, thank you so much for the info! That is very useful to know.

**Comment by YoungElPaso** [comment]
I've run into a similar situation where I have a \<details\> element which has it's open attribute set via  a prop on it's parent. If I try to measure the height of the contents without wrapping requestAnimationFrame when open is set to true, I get 0.  Guessing it's the same timing issue.

Glad to see rAF is a standard or suggested work-around for measuring elements.

Another, though more involved workaround might be to try to render a <Placeholder> element with same children, wait for first updated, measure whatever, set a prop like 'isReady' and then re-render w/ the final component template/markup. 

Just adding my 2 cents since I found this issue trying to figure out how to manipulate slotted DOM elements *before* they are actually slotted and generally trying to figure out best time to intervene in the lifecycle.

**Comment by gitaarik** [comment]
You can also actually use the `slotchange` event on `<slot>` elements. Can be useful in some situations:

https://lit.dev/docs/components/shadow-dom/#accessing-slotted-children
