### ISSUE TITLE
Using properties in <style> tag doesn't work in Firefox when using same element twice

### ISSUE THREAD

**Issue by gitaarik** [Polymer/lit-element#221]
### Description
When you have an element that uses a property as a CSS style value, and you use this element two times with a different value, then the value you set on the first element also gets used in the second element in Firefox. In Chrome it works, possibly because they have a real shadow DOM and doesn't use the webcomponents loader.

#### Live Demo
Demo: https://evanescent-tiglon.glitch.me/
Source: https://glitch.com/edit/#!/evanescent-tiglon?path=index.html

#### Steps to Reproduce
1. Create an element that has a property that is used as a CSS style value
2. Make 2 instances of this element with different values for this property
3. See the difference of the result in Firefox and Chrome

#### Expected Results
You would expect the second element to get the style you provide to it, but it gets the same style you give to the first element. It happens only in Firefox, in Chrome it works like expected.

#### Actual Results
Each element it's rendered according to the properties you set on it.

### Browsers Affected
- [x] Firefox
- [ ] Chrome

### Versions
- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by sorvell** [comment]
This is a limitation of the `ShadyCSS` library that's used to help scope styles when using `Shady DOM` to simulate real Shadow DOM. The styles for a given element type are specially scoped only one time per element definition. That's why the "first render" wins.

It's also not a particularly good for performance to render dynamic values in styles like this since altering stylesheets is pretty expensive in the browser. Instead we'd recommend using css custom properties for this. Here's an example: https://glitch.com/edit/#!/nice-coke.

**Comment by gitaarik** [comment]
Aha, clear, thank you!
