### ISSUE TITLE
Updated does not reflect the lastest property changes

### ISSUE THREAD

**Issue by mjgchase** [Polymer/lit-element#238]
#### Live Demo
https://stackblitz.com/edit/lit-element-example-kiw6fe?file=index.js

#### Steps to Reproduce
See stackblitz link above

#### Expected Results
Updated as the name suggests should provide a map of the latest property changes seems this function is fired before updateComplete

#### Actual Results
previous results are displayed

### Browsers Affected

- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.1
- webcomponents: v2.1.3

**Comment by hastebrot** [comment]
I currently have to use `this.selectedIndex` instead of `changedProperties.get("selectedIndex")`.

~~~ts
  protected update(changedProperties: PropertyValues) {
    super.update(changedProperties)
    if (changedProperties.has("selectedIndex")) {
      this._list.focusElement(this.selectedIndex)
    }
  }
~~~

**Comment by kevinpschaaf** [comment]
This is working as intended.  

[Per the current docs](https://github.com/Polymer/lit-element/blob/master/README.md#api-documentation):
> The `changedProperties` argument is a Map with keys for the changed properties pointing to their previous values.

Lifecycle callbacks taking the `changedProperties` API recently changed to only provide a map with keys containing change property names mapped to their _old values_.  Since current values are available on `this`, providing them as a map via arguments would be redundant.
