### ISSUE TITLE
connectedCallback of child element is called after connectedCallback of parent

### ISSUE THREAD

**Issue by pshihn** [Polymer/lit-element#254]
If custom element A contains child Custom Element B,
`connectedCallback` of A is called before B.
With lit-element 0.5.2, B was called before A.
(I believe the correct behavior is that B should be called before A)

#### Live Demo
With v0.6.2: https://jsfiddle.net/shihn/9yjt50k4/1/
With v0.5.2: https://jsfiddle.net/shihn/bjn5ko3m/4/
(Look at the console logs)

### Browsers Affected
All, afaik

### Versions
- lit-element: v0.6.2

**Comment by pshihn** [comment]
I'm not sure if there's anything in the spec guaranteeing the order - as these components should deal with their lifecycle independently.  (I know that older lit-element and Polymer 2.x components behaved the same way. child called before parent.)

**Comment by pshihn** [comment]
I think the root here is that `render` happens asynchronously after `connectedCallback` which wasn't the case before. 
It seems we should only use lit-element lifecycle callbacks (the native callbacks have less  meaning)?

**Comment by pshihn** [comment]
Blabbering on... 
`firstUpdated` is also called in the parent before the child.

**Comment by sorvell** [comment]
Sorry for the delayed response. There's no spec issue here. An element's `connectedCallback` is called when it's appended to the document and this is whenever the code appending the element runs. For elements within a LitElement's `shadowRoot`, this occurs when `LitElement` updates and renders. 

In version `0.5.x` rendering was done synchronously in an element's `connectedCallback`. As of version `0.6.x` rendering is asynchronous after an element is connected. This change was made for consistency, since `LitElement` generally renders asynchronously.
