### ISSUE TITLE
Multiple `update`s for an element may run during parsing depending on script type

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/lit-element#258]
### Description
If an element definition is loaded synchronously with a legacy script, `update` may be called multiple times for any main-document elements that follow the script in the page: one for any defaults set in the `constructor`, plus one for each `attributeChangedCallback`.

If an element definition is loaded using defer semantics (e.g. `type="module"` or `defer`), `update` is only called once for such elements.

The assumption that one microtask is enough to collect the constructor defaults and overrides via attributes appears to be insufficient in the first case above.

#### Live Demo
Note console logging:
* Expected (using module script): [demo](https://hushed-algebra.glitch.me/index.html), [code](https://glitch.com/edit/#!/hushed-algebra?path=index.html:8:0)
  * Update is called once
* Unexpected (using bundled legacy script): [demo](https://hushed-algebra.glitch.me/webpack.html), [code](https://glitch.com/edit/#!/hushed-algebra?path=webpack.html:7:4)
  * Update is called 4 times (ctor + 3x attributes)

It appears we need to add back the optimization (used in Polymer 2) to not flush property changes (e.g. the initial `_validate` -> `update` -> `render`) until the element has been connected, to ensure efficient startup of the element and avoid spamming the update/render lifecycles.

Applying the following stopgap `DeferUntilConnected` mixin demonstrates the expected improvements, but ideally `changedProperties` should accumulate until the actual `update`, which this does not attempt: [code](https://glitch.com/edit/#!/honey-mile?path=index.js:4:0), [demo](https://honey-mile.glitch.me/webpack.html)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 12
- [x] Safari 11
- [ ] IE 11

### Versions
- lit-element: v0.6.2

**Comment by sorvell** [comment]
OK, I think we've finally understood the issue here. A microtask checkpoint may be triggered as a result of element creation. This is noted in the spec at the end of the [Requirements for Custom Elements Constructors section](https://html.spec.whatwg.org/#custom-element-conformance).  Empirically, this appears only to occur for parser generated elements with existing definitions. 

This means that any `LitElement` that sets a property's default value in the constructor (at least if it is generated by the parser when defined) may exhibit a couple different issues: (1) update may be called more times than expected, (2) if a reflecting property is set, there may be an error `Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes`. Here's a [minimal repro](https://output.jsbin.com/nejazubawu).

Deferring updating until `connectedCallback` as suggested above should fix this issue.
