### ISSUE TITLE
As an extension provide a `bind` directive for two way data binding to a property

### ISSUE THREAD

**Issue by akc42** [Polymer/lit-element#271]
As I convert my elements over from Polymer 3 to lit element I am having to implement a lot of boiler plate handling of change events. I originally raised a suggestion on `lit-html` but it was pointed out there that a directive might be a better solution.

https://github.com/Polymer/lit-html/issues/573

Maybe lit-element could provide an extensions directory with this sort of directive for lit element (and any other appropriate ones related web components)

**Comment by sorvell** [comment]
Sorry for the delay. We're disinclined to add this to `LitElement` since we don't want to encourage use of 2-way bindings at this point because although they can make simple things easier, they become an impediment to understanding at a moderate level of complexity.

That said, we don't want users to feel like they have to write a bunch of boiler plate. Here's an example of how you could write a directive to automatically wire up an event-based 2-way binding system, similar to Polymer's. This example should also be compatible with the data events Polymer sends.

https://glitch.com/edit/#!/fantasy-desk?path=bind.js:6:0

**Comment by akc42** [comment]
Thanks for the example.  Ironically I have now completed my Polymer 3 to LitElement migration and much of the earlier boiler plate that I wrote got changed into more specific management of the situation.  In the most complex part of my application - an appointment management system - one top level management element handles all the data (storage, distribution, keeping a backend database in sync etc), but user interactions to change that data are more conveniently handled by pairs of elements working together.  One sits down the hierarchy of elements and is responsible for displaying a field value in its appropriate form.  There may be many instances of this element. The other is a (singleton) dialog management box which allows the user to change the field value.  Because these fields types are not only handled in appointments but in other parts of the application, the dialog box sits at the subsystem selection (I call page selection) level of the app and the two communicate via events.  When the ui finds out the dialog changed its value it has to communicate this fact back up to the data manager.  So with LitElement this ends up being an event, but one which bubbles all the way up the hierarchy to the data manager.

So as I slowly remove Polymer 3 elements from this heirarchy, there is less and less two way databinding going on and more longer distance events.

I am now in the process of slowly removing my dependance on `<paper-*>` elements.  I am more sceptical about whether I can remove the two way data binding dependance here.  We shall see.
