### ISSUE TITLE
customElement decorator should use type string for `tagName`

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-element#291]
This is currently `keyof HTMLElementTagNameMap` but this doesn't work nicely in TypeScript right now and the result is you have to cast to `any`. Instead we should just use `string` for now.

**Comment by jhpratt** [comment]
Seconding this. I just ran into this issue while testing out lit element on an existing component.

**Comment by jhpratt** [comment]
@nrdobie That's because that long list _is_ what `keyof HTMLElementTagNameMap` is equivalent to. That's not a wrong setting at all; lit-element currently requires you to manually extend the interface. I don't think that should be necessary, and switching to `string` would suffice (rather than casting to `any`).

**Comment by legowerewolf** [comment]
Just ran into this, would be a nice fix. @nrdobie how would changing to `string` change the behavior?

**Comment by nrdobie** [comment]
Functionally it won't but it doesn't require the HTML tag list to be
updated for TypeScript. I know I'm splitting hairs and I don't really have
a strong opinion. I can union this with string and get the best of both.

**Comment by vladnicula** [comment]
Can someone explain the reasoning for having keyof there? I don 't fully understand why this wasn't a string in the first place.

**Comment by sorvell** [comment]
Fixed via https://github.com/Polymer/lit-element/pull/292.
