### ISSUE TITLE
Re-export `unsafeHTML` from lit-html

### ISSUE THREAD

**Issue by jhpratt** [Polymer/lit-element#315]
Is there any particular reason `unsafeHTML` isn't re-exported? When using lit-elem, I shouldn't have to worry about how to import something from lit-html, because as far as I'm concerned I'm only using a single package.

What I'd like to work:
`import { unsafeHTML } from '@polymer/lit-element;`

#### Expected Results
A successful import.

#### Actual Results
Import is not found, and must be manually imported via a `lit-html`.

### Versions
- lit-element: v0.6.3

**Comment by justinfagnani** [comment]
Directives from lit-html aren't exported from lit-element.js _or_ lit-html.js itself. They're supposed to be imported if you use them, to keep bundle/network bytes size down.

**Comment by raphaellueckl** [comment]
How to do that? I'm confused.

**Comment by justinfagnani** [comment]
There's an example import in the docs: https://lit.dev/docs/templates/directives/#unsafehtml

```ts
import {unsafeHTML} from 'lit/directives/unsafe-html.js';
```

Also, we should be using the issue tracker here: https://github.com/lit/lit/issues This repo is deprecated.

**Comment by raphaellueckl** [comment]
In my case, the issue was that I needed to leave out the file ending. Could be related to the default eslint bundler or something.

`import {unsafeHTML} from 'lit/directives/unsafe-html.js';` ==> `import {unsafeHTML} from 'lit/directives/unsafe-html';`

Something like this, I can't remember exactlyt. Was in a TS project.
