### ISSUE TITLE
isolate properties, into namespace

### ISSUE THREAD

**Issue by askbeka** [Polymer/lit-element#323]
### Description
properties currently being accessed as instance props `this.propName`, making it inconvenient to pass props around, like `this.props.propName`. 
If wanted to pass properties, I would need to clean them up from all the members of the class.
And it will be a good advantage in terms of clarity, that properties are not the same as other members

In combination with [spreading in lit-html template](https://github.com/Polymer/lit-html/pull/213)
it will easier to compose components, and create Higher order components
```
html`
   <composed-component ...=${this.props}></composed-component>
   <!-- OR -->
  <composed-component ...=${{...this.props, overridingProp: 'overriden value'}}></composed-component>
`
```

**Comment by sorvell** [comment]
Thanks for the suggestion, but we're disinclined to make this change because this is not how other elements in the web platform work. For example, the `<input>` element does not have `this.props`; instead, you can read its value directly via its `value` property.

Since `LitElement` is a custom element base class, we want to encourage elements to be written that function similar to other DOM elements in the platform.

While we could add a feature like this to make it easier to pass around an element's state, I'm not sure it's something we'd want to encourage wholesale. In addition, since a user can implement a custom getter/setter and call `requestUpdate`, we don't know the complete set of an element's relevant properties.

That said, you can experiment with creating this type of API yourself in a base class you control. You could override the static `createProperty` to keep a list of properties and then implement a `props` getter that returns an object that maps the element's properties to `this.props`.
