### ISSUE TITLE
[docs] Review Lifecycle page for technical accuracy

### ISSUE THREAD

**Issue by katejeffreys** [Polymer/lit-element#355]
Review the content at https://lit-element.polymer-project.org/guide/lifecycle for technical accuracy only. 

Markdown source: https://github.com/Polymer/lit-element/blob/master/docs/_guide/lifecycle.md

* [x] find all `x: String` etc change to `x: { type: String }`
* [x] check code editor embeds openFile
* [x] put code editor embeds under correct headings
* [x] `this._updatePromise` not defined
* [x] `updateComplete` - revise this section. alternatives to overriding it/call super

**Comment by kenchris** [comment]
Should the life-cycle events explain how these fit with the Custom Element life-cycle events? Like does it ever make sense to call `connectedCallback` and if you do, do you need to call `super.connectedCallback()`?

**Comment by keanulee** [comment]
Some of the code editor embeds open index.ts on launch instead of my-element.ts/js.

Some of the code editor embeds are under the wrong heading (e.g. "Update in response to something that isn’t a property change", "Request an update for a specific property").

`updateComplete` - should we really encourage overriding it?
- If you want to wait on some state your subclass controls, then you could wait on both promises:
  ```js
  await Promise.all(this.updateComplete, this.getMoreState());
  ```
- If you _really_ override, then the result should at least use `super` or something
- Under "Do something when the element next updates", should be `await this.updateComplete` instead of `await updateComplete`

**Comment by keanulee** [comment]
- `this._updatePromise` is not defined anywhere from what I can tell
