### ISSUE TITLE
Property declared through static properties does not work with Babel class-properties spec transform

### ISSUE THREAD

**Issue by blikblum** [Polymer/lit-element#414]
### Description

When a property is declared through static properties  and its value is initialized using class property syntax, the element is not updated when the property value changes.

This occurs because the spec version of class property transform defines the variable using a Object.defineProperty which overwrite the setter added to prototype

I don't see much to do aside document and suggest use of loose: true option when using babel class property transform

_But there's a remaining question: this feature work with native class property implementation which should be spec compliant?_

#### Live Demo

https://github.com/blikblum/lit-element-decorator-tests/tree/master/babel7

#### Steps to Reproduce
1. Define a class with a property, initialized with class property syntax
```
class MyApp extends LitElement {
  static properties = {
    count: {type: Number}
  }

  count = 0

  increment = () => {
    this.count++
  }

  render()  {
    return html`<h3>Test</h3>
      <button @click=${this.increment}>Increment</button>
      <div>App value: ${this.count}</div> `
  }
}
```
2. compile using babel 7 and following plugin config:

```
const specPluginsConfig = [
  [
    '@babel/plugin-proposal-class-properties',
    {
      'loose': false
    }
  ]
]
```
#### Expected Results

Element should be rerendered on count change

#### Actual Results

Element is not rerendered on count change

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions

- lit-element: v0.6.5
- webcomponents: native

**Comment by sorvell** [comment]
Class fields are not compatible with accessors per spec. Since placing a property in `static get properties` creates an accessors, your example does not work.

There are 2 different ways to define properties and with platform support landing for class fields and decorators the `static get properties` will eventually be deprecated in the future.

With the release of version 0.7 both of these will work (Note, 0.7 specifically is adding support for Babel transpiling.):

Platform of today (does not require transpiling):
```
static get properties() {
  return {
    foo: {type: Number}
  }
}

constructor() {
  super();
  this.foo = 5;
}
```

Platform of the future (*does* require transpiling via TypeScript or Babel):

```
@property({type: Number})
foo = 5;
```

Note the `@property` decorator converts this class field into an accessor and initializes it.

Hope that helps.

**Comment by blikblum** [comment]
I'm aware of that since i'm developing a library with class properties / decorators. Just pointing for you can document (or not).

With chrome shipping the feature around the corner this case will be common
