### ISSUE TITLE
Extending does some "magic" for properties which reduces control

### ISSUE THREAD

**Issue by daKmoR** [Polymer/lit-element#450]
### Description
Why do we have this magic of "auto" merging `static get properties()` while extending? Why not use a simple ` ...super.properties`?

Doing this "magic" brings the following downsides:

1) When applying mixins that each have the same property it will execute requestUpdate for each definition.  
Use-case would be Mixins that work independently but can also be combined.
```js
const MixinA = superclass => class MixinA extends superclass {
  static get properties() { return { name: { type: String }, }; }
}

const MixinB = superclass => class MixinB extends superclass {
  static get properties() { return { name: { type: String }, }; }
}

class CustomGreeting extends MixinA(LitElement) {
// =>will execute 1 time

class CustomGreeting extends MixinA(MixinB(LitElement)) { 
// =>will execute 2 times

class CustomGreeting extends MixinA(MixinB(LitElement)) { 
  static get properties() { return { name: { type: String }, }; }
}
// =>will execute 3 times
```

2) When extending an element and using `...super.properties`  it will execute requestUpdate for each definition.  
Use-case would be changing the property type on the extending element.
```js
class MyBase extends LitElement {
  static get properties() { return { name: { type: String }, }; }
}

class ExtendGreeting extends MyBase {
  static get properties() { return { 
      ...super.properties,
      name: { type: Number},
};}
```

#### Live Demo
https://stackblitz.com/edit/lit-element-request-update-bug?file=index.html

#### Expected Results
One call to requestUpdate for changing properties.

#### Actual Results
Multiple calls to requestUpdate for each `static get properties` with the same name in the "extending tree".

### Browsers Affected
- [x] Chrome

### Versions
- lit-element: v2.0.0-rc.2

**Comment by sorvell** [comment]
Putting a property in into `static get properties` does two things: (1) it makes an accessor for the property (unless `noAccessor` is set to `true`) and (2) it stores the given metadata for the property, controlling things like whether or not the property should reflect to an attribute. 

The reason we merge the `properties` metadata from superclasses under the hood is for consistency. Since the class inherits form the superclass, it already has the accessor for a property that was in the superclass' `properties`. If we did not merge the metadata, the subclass would not have the property metadata and this could lead to unexpected behavior (e.g. why did this property stop reflecting but still trigger an update?).

It is true that by default a property that also exists in a superclass creates an accessor that wraps the superclass setter and this can cause `requestUpdate` to be called multiple times. This is done to make auto-generated accessors compose naturally with superclass accessors, whether they be user-defined or generated. However, `requestUpdate` is an extremely cheap call since all it does is request an update if one is not already pending. Further, this can be customized by putting `noAccessor` on the subclass property.

Finally, there's no reason you cannot use object spread like this to customize the metadata for a given property if desired.

**Comment by sorvell** [comment]
We're actually considering removing the property accessor wrapping entirely. Instead, if user defined accessors are used, the property metadata should include `noAccessor: true`.

This would address the issue here; however, we're not considering this change specifically because of this issue. Upon further reflection, we think it's a bit too fancy and makes any future optimization of accessor generation much harder.

**Comment by tlouisse** [comment]
Thanks for your answer. It indeed feels good from the user perspective to be able to completely control getters and setters (and optionally call `requestUpdate`).
I tried the code in your pull request and this also does the job for us (our tests are passing again 👍).
