### ISSUE TITLE
ShadyCSS seems to be applying unnecessarily

### ISSUE THREAD

**Issue by stramel** [Polymer/lit-element#484]
### Description

When including the webcomponentsjs polyfills to support all browsers, ShadyCSS seems to be applying regardless of native support for ShadowDOM.

Perhaps this is better filled under the webcomponentsjs repo?

#### Live Demo

https://stackblitz.com/edit/shady-css?file=index.html

#### Steps to Reproduce

1. Load the stackblitz repro link (https://stackblitz.com/edit/shady-css?file=index.html)
2. Observe expected result
3. Uncomment the webcomponentsjs polyfill script
4. Observe the invalid result

#### Expected Results

first line should be green
second line should be red

#### Actual Results

Both lines are green

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [N/A] Edge
- [x] Safari 12
- [ ] Safari 11
- [ ] Safari 10
- [N/A] IE 11

### Versions

- lit-element: v2.0.0-rc.5
- webcomponents: v2.2.4

**Comment by sorvell** [comment]
The intention is that template parts in style elements apply one time only and cannot be updated. 

Updating template parts in style elements is a performance anti-pattern. Updating the textContent of a style element causes the stylesheet to be re-parsed and the element to perform a full style recalculation.

In addition, it's not supported by the ShadyCSS polyfill, and we want to normalize the behavior between native and polyfilled Shadow DOM. Even under native Shadow DOM, the ShadyCSS polyfill provides support for `@apply` and this only works if we disable template parts in style elements.

It's true that you can get live template parts in style elements by not loading the ShadyCSS and ShadyDOM polyfills, but we don't encourage this for the reasons stated above.

**Comment by stramel** [comment]
> It's true that you can get live template parts in style elements by not loading the ShadyCSS and ShadyDOM polyfills

It was my understanding that the polyfill wouldn't apply if the browser supported ShadowDOM. I understand that updating template parts in style elements is an anti-pattern. However, shouldn't it work even if I include the polyfill loader, since the polyfill shouldn't be applying?

**Comment by BBKolton** [comment]
This ended up being large problem with our project. We wanted to use lit-element on the same page as a React running in a web component in browsers that natively support these technologies. However, ShadyCSS kept ripping out the style tags from the React web component, leaving us style-less. We ended up dropping support and removing all instances of lit-element because of this.

It was a while ago, but I remember seeing that lit-element was using an out of date version of ShadyCSS. ShadyCSS now supports an option to disable the runtime entirely, which would have been extremely helpful, but the version packaged with lit-element, despite saying it was the latest version, didn't support that feature.

**Comment by justinfagnani** [comment]
@BBKolton lit-element doesn't package ShadyCSS, so it can't be using an out-of-date version. Do you have a reproduction of your setup?
