### ISSUE TITLE
`render()` not called when setting decorator properties from asynchronous call

### ISSUE THREAD

**Issue by xwatkins** [Polymer/lit-element#523]
### Description
In `connectedCallback()`, I make a call to a remote API to fetch data. When the call is complete, I set a `property`: graph. This triggers a call of  `render()` as expected when using `static get properties()` but doesn't call it if I use `@property` decorators instead.

```
  async connectedCallback() {
    super.connectedCallback();
    if (this.proteins) {
      this.proteinList = this.proteins.split(",");
      const data = await fetchData(this.proteinList);
      const jsonData = await getJson(data);
      this.graph = processData(jsonData);
    }
  }
```
This works (`render()` is called when graph is updated from within component):
```
  static get properties() {
    return {
      proteins: {type: String},
      proteinList: {},
      graph: {}
    };
  } 
```
This doesn't (`render()` is not called when graph is set from within component):

```
  @property({type: String})
  proteins: string = "";
  
  @property()
  proteinList: string[] = [];

  @property()
  graph: { adjList: AdjList } = { adjList: {} };
```

#### Live Demo
https://xwatkins-multi-interaction.glitch.me/
(comment out property decorators and uncomment the static get properties method to see it working)

### Versions
- lit-element: 2.0.0-rc.5
- webcomponents: v2.2.4

**Comment by sorvell** [comment]
This looks like an incompatibility with the decorators setup on the example. Support for TC39 proposed decorators via babel (`@babel/plugin-proposal-decorators`) should be considered experimental since the spec is fairly in flux right now.

We will definitely be staying on top of these changes and updating when we can. In the meantime, you can try using the configuration in lit-element's `package.json` and/or use decorators via `TypeScript`.

**Comment by justinfagnani** [comment]
This appears to render the same with or without decorators. I think we might have fixed them at one point. Reopen if it's still an issue.
