### ISSUE TITLE
Text-fields aren't reset when using a deep clone, but are updated when the value is changed.

### ISSUE THREAD

**Issue by rickygarg** [Polymer/lit-element#538]
### Description
1. Render not called when resetting the object using JSON.parse(JSON.stringify(object))
2. Upon manually calling this.requestUpdate(), render is called, but the text-field is still not updated. Tried this with vaadin-text-field and paper-input, so posting the issue here instead of those repositories.

#### Live Demo
https://stackblitz.com/edit/lit-element-example-y71swn?embed=1&file=index.js

#### Steps to Reproduce
1. Reset a JS object or array using JSON.parse(JSON.stringify(object)).

2. Restore original text-field value based on object's value.

#### Expected Results
Text field should be reset to original value.

#### Actual Results
Text field isn't updated

### Browsers Affected

- Chrome

### Versions

- lit-element: v2.0.0-rc.5
- webcomponents: v2.0.0

**Comment by sorvell** [comment]
In both `lit-element` and `lit-html` property values are dirty checked by default. This is done for performance reasons. The rendering is not updating as you expect because of this dirty checking.

The `mood` property in the example is a string so calling `JSON.parse(JSON.stringify(object))` does not change the value since `'Good' === JSON.parse(JSON.stringify('Good'))`. Calling `requestUpdate` does force the outer element to update and render, but then `lit-html` dirty checks the value being passed to the inner element and renders no change.

The best way to fix this is to keep track of the value as it changes. This is pretty natural since normally you'd want to do something with the value entered into the input. I've modified the example as little as possible to make this happen, but there are a variety of ways to do this. Notice that as the input value changes, we send the data back through the element. Then the "reset" is actually seen as a change: https://stackblitz.com/edit/lit-element-example-brbbtm?file=myelement2.js.

For completeness, I made another example showing that it's also possible to make `lit-element` work as you initially expected where all sets are seen as changes, though we generally don't recommend this for performance reasons. In this example, the property's `hasChanged` option has been set to a function that always returns `true`. This function should return `true` when `lit-element` should see the set as a change that provokes rendering. We've also used a `directive` that forces `lit-html` always to see a set as a change. Again, we wouldn't recommend using this technique much, but here's an example: https://stackblitz.com/edit/lit-element-example-gzjt6c?file=myelement2.js.
