### ISSUE TITLE
First render event updates appear not to trigger update

### ISSUE THREAD

**Issue by zombiezen** [Polymer/lit-element#549]
### Description

Events that are triggered soon after (during?) the first render seem to not trigger an update.

#### Live Demo
https://stackblitz.com/edit/lit-element-example-xf7hpe?file=index.js

#### Steps to Reproduce

1. Observe that the console logs and DOM contents.
2. Click to make other path changes.

#### Expected Results

1. Console log should show "_pathChanged has big mood: /" and the DOM should show "Web Components are /!" on first load.

#### Actual Results

1. Console log shows "_pathChanged has big mood: /" and the DOM shows "Web Components are great!" on first load.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge

(Other browsers probably affected, but I don't have them handy.)

### Versions

- lit-element: v2.0.1
- webcomponents: v2.2.6

**Comment by kevinpschaaf** [comment]
Confirmed the issue.  If web components being rendered fire events synchronously to rendering, event handlers that set properties based on those events won't trigger a re-render.  Although we do now consider elements firing synchronous events to be an anti-pattern (we only recommend firing events as a result of UI/asynchronous actions and not synchronously on creation or property updates), legacy elements from Polymer like `<iron-location>` often did exactly that.

`LitElement`'s implementation of `update` synchronously calls lit-html `render`, and if the act of "rendering" any DOM causes synchronous events to fire and set properties, those changes won't trigger a re-render due to the contract around `update` in `UpdatingElement` (any changes to properties in `update` do not cause a second update to be scheduled).

The contact for `update` around this behavior was intentional: overriding `update` and changing properties _before_ `super.update()` is a fine pattern for e.g. resetting state based on property changes, and those changes will still be reflected in `render` since it will be called in the `super.update()`.  However, changes after rendering (i.e. after `super.update()`) should be instead done in `updated` so that they cause a re-render.

We will consider the best way to address this, either in the library or via patterns, and in the fullness of time, ensuring a community-wide pattern where elements don't fire events synchronously seems the best way forward [for a number of reasons](https://github.com/webcomponents/gold-standard/wiki/Property-Change-Events).

In the meantime, a simple solution is to `await this.updateComplete` in the event handler to ensure the property assignment triggers a re-render: 

https://stackblitz.com/edit/lit-element-example-wrnwsh?file=index.js

**Comment by zombiezen** [comment]
Makes sense, thank you for the explanation! Yeah, not immediately retriggering rendering makes a lot of sense, because then you could hang the UI thread with infinite rendering.

**Comment by katejeffreys** [comment]
Note to self to address this somehow in docs, maybe Events and/or Lifecycle pages.

**Comment by arthurevans** [comment]
Related to: #551.
