### ISSUE TITLE
Checkbox's 'checked' state does not reflect a property's value after the checkbox has been clicked

### ISSUE THREAD

**Issue by rickyattiliaaq** [Polymer/lit-element#601]
### Description
Checkbox's 'checked' state does not reflect a property's value after the checkbox has been clicked

#### Live Demo
https://stackblitz.com/edit/lit-element-example-cvtzqy

#### Steps to Reproduce
1. Create a boolean property and make a checkbox reflect its value, using the '?checked' attribute
2. Programmatically change the value of the boolean property, and observe the checkbox correctly become checked/unchecked
3. Click the checkbox
4. Again change the value of the boolean property, and observe that the checkbox no longer checks/unchecks

#### Expected Results
After clicking the checkbox, programmatically changing the value of the boolean property will result in the checkbox becoming checked/unchecked

#### Actual Results
After clicking the checkbox, it no longer becomes checked/unchecked when the boolean property changes

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 11
- [?] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.0.1
- webcomponents: v2.2.6

**Comment by mchyb** [comment]
By using `?` you are binding the property to an attribute not the `checked` property of the checkbox (more explanation [here](https://lit-html.polymer-project.org/guide/writing-templates#bind-to-attributes)). If you use dot `.` instead everything works fine. Notice that if you dropped the attribute binding and updated the `checked` attribute manually by using native `setAttribute` and `removeAttribute` methods in`updated` callback the problem still occurs.

**Comment by rickyattiliaaq** [comment]
@mchyb Ah! Thank you.
I will mark this issue as closed 👍

**Comment by HawkSK** [comment]
A really obscure problem, where once setting the `?checked` attribute works but in another case it doesn't reflect to the `.checked` property correctly leading to hard to debug and unexpected behaviour.
I noticed it by the fact in HTML seeing `<input type="checkbox" checked>` but the CSS selector `input:checked` not working.

Calling `$0.setAttribute('checked', '')` in the browser console switches the `$0.checked` property to true, so I'd expect Lit to to the same.

**Comment by justinfagnani** [comment]
@HawkSK can you make a reproduction of the behavior you're seeing on https://lit.dev/playground ?

Checkboxes respect their `checked` attribute until they're changed by user interaction, at which point they keep the state selected by the user and ignore `checked`. You probably need to bind to the checked property with `.checked=${}`.

**Comment by HawkSK** [comment]
I have [replicated it](https://lit.dev/playground/#project=W3sibmFtZSI6InRvZ2dsZS1idXR0b24udHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCd0b2dnbGUtYnV0dG9uJylcbmV4cG9ydCBjbGFzcyBUb2dnbGVCdXR0b24gZXh0ZW5kcyBMaXRFbGVtZW50IHtcblxuICBAcHJvcGVydHkoe3R5cGU6IEJvb2xlYW4sIHJlZmxlY3Q6IHRydWV9KVxuICBteUJvb2w6IGJvb2xlYW4gPSBmYWxzZTtcblxuICB0b2dnbGVNeUJvb2woKSB7XG4gICAgdGhpcy5teUJvb2wgPSAhdGhpcy5teUJvb2w7XG4gIH1cblxuICB1cGRhdGVNeUJvb2woZSkge1xuICAgIHZhciBjaGVja2VkID0gZS50YXJnZXQuY2hlY2tlZDtcbiAgICB0aGlzLm15Qm9vbCA9IGNoZWNrZWQ7XG4gIH1cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgICAgICAgXG4gICAgICAgIDxwPlxuICAgICAgICAgIG15Qm9vbDogPGlucHV0IHR5cGU9XCJjaGVja2JveFwiID9jaGVja2VkPVwiJHt0aGlzLm15Qm9vbH1cIiBAY2xpY2s9XCIke3RoaXMudXBkYXRlTXlCb29sfVwiIC8-ICgke3RoaXMubXlCb29sfSlcbiAgICAgICAgPC9wPlxuXG4gICAgICAgIDxwPlxuICAgICAgICAgIDxidXR0b24gQGNsaWNrPVwiJHt0aGlzLnRvZ2dsZU15Qm9vbH1cIj5Ub2dnbGUgbXlCb29sIHZhbHVlPC9idXR0b24-XG4gICAgICAgIDwvcD5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vdG9nZ2xlLWJ1dHRvbi5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDx0b2dnbGUtYnV0dG9uIG15Qm9vbD48L3RvZ2dsZS1idXR0b24-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d) based on OP's example.

Yes, I solved the issue by actually binding both `.checked` and `?checked` so it's also visible in the DOM and works correctly. Or could this collide and I should use only `.checked`?

Honestly, I missed the behaviour of the native input ignoring the DOM attribute after user interaction. I was just so immersed in reflected boolean properties that it didn't cross my mind.

Maybe it would be an interesting note in the Lit documentation (f.e. [here](https://lit.dev/docs/v1/lit-html/writing-templates/#bind-to-attributes) ) to guide people in the difference between setting a boolean attribute and a boolean property. Because my first assumtion is: Oh it's a boolean so I use `?notation`.

**Comment by nboisteault** [comment]
I'm only using lit-html not lit element so I might have missed something in this [example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcblxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIHN0YXRpYyBwcm9wZXJ0aWVzID0ge1xuICAgIG5hbWU6IHt0eXBlOiBTdHJpbmd9LFxuICB9O1xuXG4gIGNvbnN0cnVjdG9yKCkge1xuICAgIHN1cGVyKCk7XG4gICAgdGhpcy5uYW1lID0gJ1NvbWVib2R5JztcbiAgICB0aGlzLnN0YXRlID0gdHJ1ZTtcbiAgfVxuXG50b2dnbGUoKXtcbiAgdGhpcy5zdGF0ZSA9ICF0aGlzLnN0YXRlO1xuICB0aGlzLnJlbmRlcigpO1xufVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGA8aW5wdXQgLmNoZWNrZWQ9JHt0aGlzLnN0YXRlfSB0eXBlPVwiY2hlY2tib3hcIj48YnV0dG9uIHN0eWxlPVwiaGVpZ2h0OjIwcHhcIiBAY2xpY2s9JHsoKSA9PiB0aGlzLnRvZ2dsZSgpfT48L2J1dHRvbj5gO1xuICB9XG59XG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3NpbXBsZS1ncmVldGluZycsIFNpbXBsZUdyZWV0aW5nKTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ) but as you can see the checkbox state does not change even if its `checked` property is bind via `.checked`.

What did I missed?

**Comment by AndrewJakubowicz** [comment]
Hi @nboisteault,

Your example works after changing the `state` field to a reactive property & removing the explicit call to `render()`, letting the [reactive lifecycle](https://lit.dev/docs/components/lifecycle/#reactive-update-cycle) handle the change. [Modified example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcblxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBwcm9wZXJ0aWVzID0ge1xuICAgIHN0YXRlOiB7dHlwZTogQm9vbGVhbn0sXG4gIH07XG5cbiAgY29uc3RydWN0b3IoKSB7XG4gICAgc3VwZXIoKTtcbiAgICB0aGlzLnN0YXRlID0gdHJ1ZTtcbiAgfVxuXG50b2dnbGUoKXtcbiAgdGhpcy5zdGF0ZSA9ICF0aGlzLnN0YXRlO1xufVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGA8aW5wdXQgLmNoZWNrZWQ9JHt0aGlzLnN0YXRlfSB0eXBlPVwiY2hlY2tib3hcIj48YnV0dG9uIHN0eWxlPVwiaGVpZ2h0OjIwcHhcIiBAY2xpY2s9JHsoKSA9PiB0aGlzLnRvZ2dsZSgpfT48L2J1dHRvbj5gO1xuICB9XG59XG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3NpbXBsZS1ncmVldGluZycsIFNpbXBsZUdyZWV0aW5nKTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)


Alternatively, if you do not want changes to `state` to trigger a reactive update by default, you can replace `this.render()` with `this.requestUpdate()`.

**Comment by nboisteault** [comment]
Hi @AndrewJakubowicz 
Thank you for your help.
I'm using lit-html in my project where the bug occurs. Do you know if there is a sandbox for lit-html as a standalone?

**Comment by nboisteault** [comment]
Ok I found a bug elsewhere in my code which induced this problem. Sorry for the noise and thanks for `lit`!

**Comment by nicolasr75** [comment]
Hi @AndrewJakubowicz ,
if you click the checkbox and then click the toggle button, the checkbox is not toggled. You have to press a second time to toggle it. But this is crucial for my code. 

I have a form to edit some item, f.e. a list of devices and the form allows the user to edit the properties of the selected device. When the user has clicked the checkbox and then selects another device, I expect loading the device properties into the form to correctly set the checkboxes. But that does not work as can be shown in your example.

I tried reflecting the click back to my property like this but it still does not work:
```
<mwc-checkbox .checked="${this.active}"
          @change="${e => this.active = e.target.checked}"></mwc-checkbox>
```

Is there anyway to fix this besides setting the DOM checked property explicitly? (which would make the property binding useless)
