### ISSUE TITLE
Default converter for Array types does not work with objects as elements

### ISSUE THREAD

**Issue by arasmus8** [Polymer/lit-element#604]
### Description

Default converter for Array types does not work with objects as elements.

The default Array Converter converts its elements to strings by simple casting. The documentation (https://lit-element.polymer-project.org/guide/properties) says however:

For Objects and Arrays, when the property is:

- null or undefined, remove the attribute.
- Defined and not null, set the attribute value to JSON.stringify(propertyValue).

Either the documentation should be changed, or the behavior changed to match the documentation.

#### Live Demo
https://stackblitz.com/edit/lit-element-example-a37cfp

#### Steps to Reproduce
- Create an element with a property of type Array
- Include the element in another element, setting the corresponding attribute to an Array with objects as elements: 
`````
html`<my-element my-attr=${ [ { key: 'val') } ] }></my-element>`
`````
- This renders as `<my-element my-attr="[object Object]"></my-element>`
- The attribute cannot be deserialized

#### Expected Results
The attribute should be converted to JSON as specified in the documentation.

`<my-element my-attr='[ { "key": "val" } ]'></my-element>`

#### Actual Results
`<my-element my-attr="[object Object]"></my-element>`

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: 0.7.1
- webcomponents: v2.2.3

**Comment by jishnukoottala** [comment]
I also faced the same issue, actually the library should support the objects as elements, Workaround as of now is to stringify your whole array and pass it  `<shopping-list-ul items="${JSON.stringify(this.items)}">`

**Comment by pshihn** [comment]
i find it easier to use these as properties. Very little value comes from attributes for complex objects. Properties are also faster. 

```
<shopping-list-ul .items="${this.items}"></shopping-list-ul>
```

**Comment by pshihn** [comment]
@arasmus8 in your example you're also mapping `complexList` to `complex-list` attribute. Polymer lib did that, but afaik, lit-element does not do that translation

**Comment by sorvell** [comment]
I believe this is working as intended. Let me explain by going back to basics. Elements can have properties and attributes and LitElement helps reflect values between these. This is convenient because HTML contains attributes, not properties. That said, as noted above, with lit-html we do have a declarative syntax for setting properties. So, using lit-html, to set an attribute `items=${value}` or a property `.items=${value}`. Generally, when passing data to another element in `render` using properties is better since properties can have any type. Using attributes is usually only necessary for styling and requires serializing/deserializing to a string.

When you say a property is `type: Array`, this makes LitElement reflect the attribute (which is always a string) to a property via `JSON.parse(attributeValue)`. Likewise, LitElement will stringify property to the attribute value if `reflect: true` is set via `JSON.stringify(propertyValue)`.

Putting this together, if you really wanted to pass an array value as an attribute using lit-html, you'd have to do: `items=${JSON.stringify(propertyValue)}`. Again, we wouldn't generally recommend this because passing the property is much simpler (`.items=${propertyValue}`).

Hope that explains it.

**Comment by arasmus8** [comment]
While I have no problem changing my code to use a property instead (and have done so), I would certainly like to encourage the team to update the documentation to match the intended behavior instead of misleadingly suggesting that the default converter build into lit-element can be used on Array or Object type values when they simply don't work.

**Comment by abraham** [comment]
I think the Polymer team is always interested in feedback and making the docs better. I'm not sure if this is necessarily in the LitElement area of responsibility though. The docs do specify `attributes are always strings` (a platform requirement) so `MyElement` has to handle converting it's `complexList` to a string to or JavaScript will coerce it. The default converter for `SubComponent`'s `complexList` is trying to working as expected but it's getting `"[object Object],[object Object]"` instead of valid JSON.

Maybe adding a note to [convert between properties and attributes](https://lit-element.polymer-project.org/guide/properties#conversion) that type conversion is only applied to an instance itself, not when properties are used in a child element would help clarify?
