### ISSUE TITLE
Events in Shadow DOM Question

### ISSUE THREAD

**Issue by MVSICA-FICTA** [Polymer/lit-element#662]
Recently, I came across the "Events in Shadow DOM" section in the following excellent article: 

https://www.dannymoerkerke.com/blog/web-components-will-replace-your-frontend-framework

I'm just getting to know lit-element and I'm concerned that the Shadow DOM might obstruct what I've had in mind? Essentially, I just want to query for DOM nodes that have the same data-attr prefix and return these as an array. The array would then be processed with RxJS, which would then react to any streamed events coming from the nodes in a given query.

Hopefully this style of reactive event capture can work without to much fuss?

**Comment by MVSICA-FICTA** [comment]
Is normal node query complicated by the Shadow DOM or not? If so what are the workarounds if any?

**Comment by jsilvermist** [comment]
If I understand you correctly, you could just select from the shadowRoot instead of the document, so from a custom element you could just do `this.shadowRoot.querySelectorAll(...)` or from document level if you want to get a certain node inside of custom elements, you could do `document.querySelectorAll('my-element')[*i*].shadowRoot.querySelectorAll(...)`.

**Comment by MVSICA-FICTA** [comment]
Thanks for the clarification and confirmation.
