### ISSUE TITLE
Using Mixins with Properties in Typescript fails (incorrectly extends base class)

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/lit-element#667]
#### Steps to Reproduce
    const MixinA = superclass => class MixinA extends superclass {
        static get properties() { return { a: { type: String }, }; }
    }

    const MixinB = superclass => class MixinB extends superclass {
        static get properties() { return { b: { type: String }, }; }
    }

    class Test extends MixinB(MixinA(LitElement)) {
        static get properties() { return { name: { type: String }, }; }
    }

#### Expected Results
Should work

#### Actual Results
    Class static side 'typeof Test' incorrectly extends base class static side 'typeof MixinB'.
    Types of property 'properties' are incompatible.
      Property 'b' is missing in type '{ name: { type: StringConstructor; }; }' but required in type '{ b: { type: StringConstructor; }; }'.ts(2417)

**Comment by e111077** [comment]
That's because the mixin props are not including the props of their superclass. You're effecively redefining the properties block each time. Here's a working solution that distributes the props into the new object:

```ts
const MixinA = (superclass:typeof LitElement) => class MixinA extends superclass {
  static get properties() {
    const superProps = super.properties;
    return { ...superProps, a: { type: String }, };
  }
}

const MixinB = (superclass:typeof LitElement) => class MixinB extends superclass {
  static get properties() {
    const superProps = super.properties;
    return { ...superProps, b: { type: String }, };
  }
}

class Test extends MixinB(MixinA(LitElement)) {
  static get properties() {
    const superProps = super.properties;
    return { ...superProps, name: { type: String }, };
  }
}
```

**Comment by jogibear9988** [comment]
kay, but it works so,

but the code also works without doing this, so why is it needed ?

**Comment by e111077** [comment]
Heya, I don't understand what you mean by it working; when I gave it a try, the typescript would not compile. I'd have to look into it a bit more when I'm back in the office to see as to why this would work in plain JavaScript.

Though, the compilation error is more of a typescript inheritance question than a lit-element issue.

**Comment by jogibear9988** [comment]
I've done like this https://polymer-library.polymer-project.org/3.0/docs/devguide/custom-elements#defining-mixins

and it sais nowhere that I need to return the properties via super, but the property worked (it readed the value from the attribute)

so I thought it's only a typescript problem that I need to define all properties in the derived class...

if I do it like you described, it will decrese the perf. of the component a litte, or am I wrong?

**Comment by jogibear9988** [comment]
Maybe then the general documentation for impl. properties should be:

   static get properties() {
      return { ...super.properties, name: { type: String }, };
    }

and will it work with the decorators?

**Comment by e111077** [comment]
Heya I looked into it. It seems as if lit recurses through the `super` chain of properties and collates them properly in a Set, so you don't have to write it like I had to make it work in vanilla javascript. Though, subclassing a class and overriding a property in typescript means that the property must have the same type or must be a superset of the super class' property.

Come think of it, you may be able to write what you have already by explicitly specifying the return type of `properties`. Though, that's more of a question for a Typescript support channel rather than on this issue.

Though, I don't see why this would not work with the `@property` decorator as you have written in your example. It should work just as you would expect it to since it's a function call rather than an override to a static property on a class.
