### ISSUE TITLE
Roadmap & News

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/lit-element#738]
As nothing happend to the polymer blog & website in the last 5 months, I wanted to know, is there a new roadmap available?
Why was no polymer summit last year?
Are new features planed?
What about successor components for example for iron-list?

**Comment by web-padawan** [comment]
> What about successor components for example for iron-list?

See https://github.com/PolymerLabs/uni-virtualizer

**Comment by jogibear9988** [comment]
@web-padawan How do I do lazy loading of data? (data virtualization?)

**Comment by web-padawan** [comment]
@jogibear9988 let's discuss the aside questions in other places.

**Comment by web-padawan** [comment]
Existing roadmap for Polymer project is quite outdated: https://github.com/Polymer/project 

There has been recently some news by @e111077 regarding Material Web Components getting some pace after a couple of months, which is a good sign.

But overall I still feel that Polymer project is lacking a proper public roadmap.

**Comment by graynorton** [comment]
Agreed, we are overdue for an update.

**Comment by jogibear9988** [comment]
@graynorton yeah, a update would be nice.

**Comment by jogibear9988** [comment]
will anything happen about this?

**Comment by graynorton** [comment]
Yes, but it may be another couple of weeks. It has been an eventful year with things outside the public eye demanding much of our attention. The dust is beginning to settle, and we're doing some planning now that should enable us to update our public roadmap with a decent level of confidence. Please hang in there a bit longer, and thanks for your patience!

**Comment by thescientist13** [comment]
potentially related, but there is a thread to reboot webcomponents.org as well, which may have a lot of overlap / correlation with the general ecosystem around Web Component tools and libraries.  Might be worth following that thread as well, for those interested.
https://github.com/webcomponents/webcomponents.org/issues/1250

**Comment by jogibear9988** [comment]
@graynorton maybe now you have a timeframe?

**Comment by graynorton** [comment]
Quick status update, since I missed my deadline...I have a draft in review by other folks on the team, aiming to publish tomorrow.

**Comment by graynorton** [comment]
We pushed the update yesterday afternoon...thanks for your patience! We'll aim to update the roadmap at least monthly going forward.

https://github.com/Polymer/project/blob/master/Roadmap.md

**Comment by jogibear9988** [comment]
@graynorton 
wasn't there also the plan to relaunch https://www.webcomponents.org/
i thought I read this some time ago...

and any news about the time schedule for material web components?

**Comment by abraham** [comment]
There is an open issue for future features of webcomponents.org.

https://github.com/webcomponents/webcomponents.org/issues/1250

**Comment by AndreasGalster** [comment]
> We pushed the update yesterday afternoon...thanks for your patience! We'll aim to update the roadmap at least monthly going forward.
> 
> https://github.com/Polymer/project/blob/master/Roadmap.md

Just a friendly poke that the roadmap could use more frequent updates 🤗

**Comment by jogibear9988** [comment]
also polymer blog is nearly dead...

which people do still work on polymer or lit?
will there be a summit next year?

**Comment by e111077** [comment]
Hello, sorry for the frustration, but the roadmap seems to still be on track. Lots of progress has been made, but generally incremental.

In our next update you may see our goals shaping up a but more.

To answer the question about who works on what, it's mostly all lit with bug fixes and performance improvements to Polymer on the side.

In terms of a summit, it's too early to tell as we are still busy with organizing local web components meetups. If you're interested in managing a Web Components <city>, please message webcomponentssf on Twitter with your interest.

We ask that you please hang on with us as this part of the year is typically filled with American holidays and catching up on work in between them (including our tech writers).

**Comment by jogibear9988** [comment]
how many people work on that projects? seems to me most of the old ones left?

**Comment by graynorton** [comment]
Hi, @jogibear9988.

Though our focus and our strategy have evolved over time, the project is still going strong and the team working on it has changed a lot less than you might think.

It's true that some of our more visible public faces from various points in time have changed roles or moved on. For example: Matt McNulty still oversees our work but his scope has increased significantly and he's less involved day-to-day; Taylor Savage is no longer at Google; Monica Dinculescu has moved to a different team at Google, doing amazing things at the intersection of MS and art; Rob Dodson is still working in Web DevRel, but is focused mainly on things other than Web Components.

But aside from high-visibility changes like these, we've enjoyed remarkable stability over the ~7 year history of the project. As a matter of policy, teams at large companies like Google don't tend to share specific staffing numbers in public, but I can tell you that we've experienced only typical, modest turnover and size fluctuation. Virtually all of the founding members are still working on the project, and there has been great continuity in the primary architects and most prolific contributors (especially to our core libraries).

It's also true that we have been blogging less (and have otherwise keeping a lower public profile) than at previous points in our history. This is largely a function of changing needs. We had to build a lot of stuff and make a lot of noise to bring Web Components to fruition, but now that they have landed across browsers, we've been able to scale back in some obvious ways. Doing so has enabled us to shift focus, and just as importantly it has created space for other advocates of Web Components and close-to-the-platform web development (e.g. Salesforce, Ionic, open-wc...) to step up. This excerpt from a mid-2018 blog post still summarizes the shift pretty well:

> First, we see web components becoming increasingly mainstream—they'll be natively supported in three of the four major browsers by year's end and are enjoying unprecedented support from other libraries, frameworks and tools. We'll keep working to eliminate barriers to adoption, as exemplified by our current effort to help the web components ecosystem move to ES Modules and npm.

> At the same time, we see our own offerings becoming lighter and more loosely coupled. Since day one, our guiding vision has been: make it simpler to develop web components, while adding minimal weight. Along the way, we've made compromises, increasing the size and scope of the library in the interest of performance or developer productivity. Our next offerings will swing back toward that guiding vision.

> Finally, with the core web components standards firmly established, we see opportunities to help shape and advocate for a new generation of related standards—standards that will bring improvements to styling and theming, templating, and loading, among other things.

All of that being said, we actually have started incrementally ramping up our public advocacy efforts (starting with a new series of local Web Components meetups, as Elliott mentioned), so stay tuned–just don't expect the future to look exactly like the past. Our vision and mission persist, but our product offerings and publicly visible efforts have evolved and will continue to do so.

**Comment by jogibear9988** [comment]
@graynorton it is still so silent around lit & polymer.
Are there any News? Whats planned? What about features we rely on? Like AdoptedStylsheets?
What are the News about Styling ShadowDom? Are there new concepts from the browsers comming? (Missing @apply)
