### ISSUE TITLE
native Lifecycle should be documented

### ISSUE THREAD

**Issue by SampsonCrowley** [Polymer/lit-element#739]
I think we need to document somewhere that `super` is required when using the native lifecycle callbacks (`connectedCallback`, `disconnectedCallback`). It took me a second when I implented them and it broke the component to realize that litElement uses them for setting up the element.

I also think there should be at least one more litElement callback: `beforeDisconnected`

Preferrably two: `afterConnected` and `beforeDisconnected`

there is currently a lifecycle event for the first update `firstUpdated` where you can easily run setup tasks without needing to remember to call super (although the name makes it ambiguous on when it is called and makes me think that it will only run if there are properties that get updated after their original constructor values are set), but there is not a callback for teardown events (e.g. `removeEventListener`)

It would be much more intuitive for users if there were just two documented lifecycle hooks that they didn't need to worry about accidentally breaking the normal litElement setup scheme

I'd be happy to setup a PR; this would take a total of two lines of code to implement if we leave it up to the end user to make sure their usage doesn't break the elements

**Comment by justinfagnani** [comment]
I think documenting the standard lifecycle methods and the requirements for overriding there is good. cc @arthurevans for that.

I'm quite unsure about new callbacks like `beforeDisconnected` that exist mainly so you don't have to call `super.x()`. `firstUpdated` exists because to implement with `updated()` you need some boilerplate state management. `updated` itself exists because of the bookkeeping needed to only be called if `shouldUpdate` returned true and if `update` didn't throw (see `performUpdate`).

**Comment by SampsonCrowley** [comment]
@justinfagnani to me it's about having a single point of entry for set up and teardown that doesn't put the burden of remembering what the library needs on the user, not just so I don't have to type super.

but the most important is documenting the native events

**Comment by danielbarion** [comment]
Yeah, just waiting @arthurevans;

PR #730

**Comment by danielbarion** [comment]
@SampsonCrowley, can you give a feedback please ? Issue solved ?

**Comment by SampsonCrowley** [comment]
@danielbarion good enough for me
