### ISSUE TITLE
LitElement lifecycle timing issue

### ISSUE THREAD

**Issue by ruphin** [Polymer/lit-element#763]
### Description
When awaiting a resolved promise in the connectedCallback, the first `render` call either did or did not yet occur, depending on the browser. Chrome will always perform an initial render before resolving any promises created in the connectedCallback, but Firefox and Safari may resolve promises in the connectedCallback before performing the initial render.

#### Live Demo
Open this page in Chrome, Firefox, and Safari:
https://codepen.io/ruphin/pen/JgOaKP?editors=1010

In Chrome, the resolution order will be
CONNECTED CALLBACK
RENDER
PROMISE RESOLVED

In other browsers, the resolution order will be
CONNECTED CALLBACK
PROMISE RESOLVED
RENDER

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 11

### Versions
- lit-element: v2.2.1

**Comment by 1player** [comment]
This might be related to some weird bug I'm seeing.

I have a LitElement wrapping a <textarea>, and hooking onto it in the `connectedCallback` method. Example:

```
<lit-element>
  <textarea>foo</textarea>
</lit-element>
```

On Firefox, `this.querySelector('textarea')` on the callback always returns an element, on Chrome it only does _sometimes_ — I can't reproduce the timing problem exactly, it seems to work as intended when the element has been loaded via AJAX, but don't quote me on that.

**Comment by ruphin** [comment]
What you are seeing is most likely an unrelated issue.

In the `connectedCallback` there are no guarantees that your children have been attached. 

The browser constructs the DOM tree in parsing order, and if it encounters any custom elements, these are connected before their content is parsed and connected. This means that if your custom element is loaded and defined before a document is parsed, the `connectedCallback` will be called before the children are attached. Aside from the loading order, it also depends on if the element is inside a document body, or if it is being cloned from a template or something like that.

I have a demonstration of this here: https://codepen.io/ruphin/pen/omjYQj?editors=1001

The correct method to interact with your children is to use the `slotChanged` event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event

**Comment by justinfagnani** [comment]
@ruphin I suspect that the change in order you're seeing might be because of a spec change for async/await where await now enqueues a single microtask, where before it would enqueue 3 microtasks because of some internal waits for the Promise value. This update was implemented in Chrome, which I think means that the update microtask is enqueued by the time `super.connectedCallback()` returns in Chrome, but in other browsers it's an internal microtask that later enqueues the actual update microtask, so your Promise is able to go first.

I have a change in the has-connected branch that removes await from the path of setting the update Promise which might fix this issue. Can you try out that branch?

**Comment by sorvell** [comment]
In general you should rely on the `updateComplete` promise in cases like this since there's no guarantee that uncoordinated microtasks execute in any particular order.
