### ISSUE TITLE
is there a way in which I can write the templet in an individual file?

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#773]
```js
import { LitElement, html } from 'lit-element';

class MyElement extends LitElement {
  render(){
    return html`
      <div>
        <p>A paragraph</p>
      </div>
    `;
  }
}
customElements.define('my-element', MyElement);
```

Hi, guys.

If the content of the template is too much, can I move them to an individual file?

**Comment by jridgewell** [comment]
```js
// template.js
import { html } from 'lit-element';

function render() {
  return html`
    <div>
      <p>A paragraph</p>
    </div>
  `;
}

// element.js
import { LitElement } from 'lit-element';
import { render } from './template.js';

class MyElement extends LitElement {
  render(){
    return render.call(this);
  }
}
customElements.define('my-element', MyElement);

**Comment by zzzgit** [comment]
Yes, I can move the method to an individual file but not the definite template itself. It's a pity, because it's not declarative enough due to bad syntax-highlight-support for markup in template literal by IDE.

**Comment by CaptainCodeman** [comment]
> If the content of the template is too much, can I move them to an individual file?

In my experience, this can often be a sign that the component is trying to do too much and could benefit from splitting into smaller components.

The biggest 'chunk' in elaborate components is often the CSS, but I just put that last in the class, template ahead of it (as they go together logically), all the API (props, lifecycle and logic) at the top.

**Comment by jordanaustin** [comment]
> Yes, I can move the method to an individual file but not the definite template itself. It's a pity, because it's not declarative enough due to bad syntax-highlight-support for markup in template literal by IDE.

As a note, there are many plugins to provide correct syntax highlighting now. You can take a look at these for VS Code: https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin or https://marketplace.visualstudio.com/items?itemName=bierner.lit-html

**Comment by justinfagnani** [comment]
@zzzgit It's really worth pointing out that lit-html templates inextricably _are_ JavaScript expressions. They cannot be put into HTML files (which I think is what you're asking) anymore than any other JavaScript could be, including similar things like JSX.

lit-html doesn't have it's own expression language, and would have to invent one, along with a parser and evaluator, in order to have a HTML-syntax variant. There's an issue for that though: https://github.com/Polymer/lit-html/issues/867

If, however you don't have any expressions at all in your template, then you don't need lit-html and you could use UpdatingElement directly and maybe fetch a template .html file and innerHTML it into your shadow root.

And if tooling is the complaint, the VS Code plugin that @jordanaustin pointed you to is amazing.
