### ISSUE TITLE
How can you access the value of props in constructor and style getters?

### ISSUE THREAD

**Issue by NadeemShakya** [Polymer/lit-element#786]
Consider the following case:
```
// parent-component.js
render() {
   return html`
       <child-component color="white" value="some value"></child-component>
  `
}


// child-component.js
class ChildComponent extends LitElement {
   static get properties() {
     return {
       value: { type: string },
       color:{ type: string }
    }
  }

  static get styles () {
    return css`
       color: ${unsafeCSS(this.color)} // this.color is undefined
    `
 }
    constructor() {
       super();
      console.log(this.value) // this.value is undefined
   }


   render() {
      console.log(this.value) // this.value is equal to some value
     console.log(this.color) // this.color is equal to white
   }
}
```

How can I access the values passed from the parent component in constructor and the style getters? This is important to set the style of a child component dynamically

**Comment by danleyb2** [comment]
the styles property is static.
dynamic styling tied to properties would require inline styles in a <style> element in your template in `render` so that different CSS rules are evaluated per instance.

the constructor is always called far before the attributes are reflected to the properties so you might need other means like `firstUpdated` for what you want to do
