### ISSUE TITLE
Ignored font-face declarations in styles

### ISSUE THREAD

**Issue by heruan** [Polymer/lit-element#793]
### Description
Despite declaring a new `@font-face` in element `styles`, it gets ignored.

#### Demo
```typescript
import { LitElement, TemplateResult, CSSResult, html, css, customElement, property } from 'lit-element';

@customElement('my-logo')
export class MyLogo extends LitElement {

  static get styles(): CSSResult {
    return css`
      @font-face {
        font-family: 'MyFont';
        src: url('../fonts/MyFont.eot');
        /* Other src */
      }
      :host {
        font-family: 'MyFont';
      }
    `;
  }

  render(): TemplateResult {
    return html`<div>This should use MyFont!</div>`;
  }
}
```

#### Steps to Reproduce

Create a component as shown.

#### Expected Results
Text displays in the correct font.

#### Actual Results
Text display in default browser font.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v2.1.0

**Comment by justinfagnani** [comment]
LitElement doesn't do anything with style contents. You might be seeings differences is how Chrome and Safari scope `@font-face`. Does it work in Safari?

**Comment by heruan** [comment]
Thank you Justin, I thought LitElement/`css` somehow processed the styles and was ignoring `@font-face`. Indeed it works in Safari, but I see no request for the font file 🤔

**Comment by lakshay35** [comment]
I have the same exact issue. I've tried creating a style element and adding to the head of the document but I still don't get the request to dispatch.

**Comment by justinfagnani** [comment]
Closing, since we don't modify the styles. Maybe there's a Chrome issue for this already?

**Comment by regnou** [comment]
hi, I would like to understand better the origin of this issue. I mean, how could a 'google' tecnology work better on safari ? And how am I supposed to create my web-components, without having the icon nicely apearing in the browser when I am crafting it ? Should I understand, that also, for production mode, after a build, I would not have the @face-font working ? It is because I need to use the material icons, and yep, they doesn t render in chrome (but yes in safari). If I need to find it in the chrome issue I don t know how to look for it, because it just happen when I use the render method of litElement finally... Tks...

**Comment by lakshay35** [comment]
Just know that you can import an external stylesheet with relative import statments inside the css file. And then make sure you have the font defined for one of your styles on the first page that is rendered in chrome like ```font-family: 'Custom Font'``` or a class for an icon if you are importing fa-icons. You have to do this because the browser only analyzes the dom once for fonts at load time. It does it only once to conserve network requests.

**Comment by lakshay35** [comment]
> hi, I would like to understand better the origin of this issue. I mean, how could a 'google' tecnology (litElement) work better on safari ? And how am I supposed to create my web-components, without having the icon nicely apearing in the browser when I am crafting it ? Should I understand, that also, for production mode, after a build, I would not have the @face-font working ? It is because I need to use the _material design icons_, and yep, they doesn t render in chrome (but yes in safari). If I need to find it in a chrome issue, I don t know how to look for it, because it just happen when I use the 'render' method of litElement finally (it works on a normal html page without using the litElement). Tks... (related question: https://stackoverflow.com/questions/57948574/why-litelement-renders-method-do-not-display-the-material-icon)

Just know that you can import an external stylesheet with relative import statments inside the css file. And then make sure you have the font defined for one of your styles on the first page that is rendered in chrome like ```font-family: 'Custom Font'``` or a class for an icon if you are importing fa-icons. You have to do this because the browser only analyzes the dom once for fonts at load time. It does it only once to conserve network requests.
