### ISSUE TITLE
Miss styles in styles() when use createRenderRoot method

### ISSUE THREAD

**Issue by danielbarion** [Polymer/lit-element#797]
### Description
Just a question, when I use `createRenderRoot ` and return the `this` to doesn't scope the component with shadow DOM, the `static get styles` doesn't work anymore ? This information are listed in this section of docs `template -> Specify the render root`.
The examples in docs doens't have any style.

The style inside `html` render function works fine, just the static method aren't work;

#### Steps to Reproduce
1. Create `my-element` with shadowDOM using static get styles to style him
2. Add `my-element` to the body
3. Use `createRenderRoot `  to render the component without shadowDOM
4. Try style him with `static get styles`

#### Actual Results & Expected Results
![https://i.imgur.com/NGSrB2M.png](https://i.imgur.com/NGSrB2M.png)

The first field are the actual result without shadowDOM, the second, has shadowDOM.

### Browsers Affected
- [x] Chrome (tested only in chrome)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v2.2.0
- webcomponents: vX.X.X

**Comment by justinfagnani** [comment]
Yeah, static styles won't work because we don't have anywhere to put them.

Inline styles "work" in the sense that they're added to the DOM, but there's no scoping so they leak all over the containing scope, and they're duplicated for every element of that class in the scope, which is perf issue.

Generally styles at all with an overridden `createRenderRoot` returning `this` is going to behave badly.

**Comment by danielbarion** [comment]
Okay, Thank you,

Got it.
