### ISSUE TITLE
use proxy API in favor of Object.defineProperty

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-element#812]
I defined a property:

```js
	static get properties() {
		return {
			fooo: {type: Array},
		}
	}
```

and then I try to push something into that array in a listener. The UI will not be updated automatically after the binding array have been mutated.

I found that in the source code, you use `Object.defineProperty` to make it reactive. [this line](https://github.com/Polymer/lit-element/blob/78e19f42b3d23700351cce4f932657e06c4abfc1/src/lib/updating-element.ts#L311)

I think you should use [Proxy API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) in favor of `Object.defineProperty` to make it more reactive. That's also what `Vue` is [trying](https://www.vuemastery.com/courses/advanced-components/evan-you-on-proxies/) in the next major version.

**Comment by Westbrook** [comment]
The array type is not having a new identity assigned when using `Array.push()` so you'll need to use `this.fooo = [...this.fooo, newItem];` to update the identity to trigger a render.

**Comment by septatrix** [comment]
I also stumbled over this when trying to implement an `<input type="json">`.
Mutating objects properties or array indices will not trigger an update because the identity itself does not change as stated above.

Instead one has to resolve to creating new objects/arrays and overwriting the old one or mutating the old object an manually triggering an update. This can be done multiple ways:

- Using the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
  ```javascript
  changeProperty(key, value) { // works like this.obj[key] = value
    this.obj = { ...this.obj, [key]: value }
  }
  pushItem(item) { // work like this.array.push(item)
    this.array = [ ...this.array, item ]
  }
  ```
  These constructs however get more complicated if you want to change elements in the middle of an array. This would require you to split the array and the insert the new element in the middle

- Forcing an update using [requestUpdate](https://lit-element.polymer-project.org/api/classes/_lib_updating_element_.updatingelement.html#requestupdate)
  ```javascript
  changeProperty(key, value) { // works like this.obj[key] = value
    this.obj[key] = value
    this.requestUpdate('obj', null)
  }
  pushItem(item) { // work like this.array.push(item)
    this.array.push(value)
    this.requestUpdate('array', null)
  }
  ```
  Using `null` or similar (empty object/array should also work) forces a complete update as far as I can tell.
  You could also create a copy using `JSON.parse(JSON.stringify(this.obj)) // or this.array` or the spread syntax `const copy = { ...this.obj } // or [ ...this.array ]`
  The first option however does not respect classes etc.

- Using a library for immutable structures (like [Immutable.js](https://github.com/immutable-js/immutable-js))
  I don't have code example though, because I have not played enough with this approach yet.

As far as I know all of these approaches suffer from the same problem - the whole property will get updated. Therefore I also think using the Proxy API would be beneficial. However this would sadly break compatibility with IE. (Though we could use the same approach as Vue is planning to take which is shipping to versions...)

**Comment by justinfagnani** [comment]
We don't want to add a full state management to system to LitElement, to keep the core small and allow for different opinions. MobX is a great solution that provides deep object observation, and there's a nice integration for LitElement here: https://github.com/adobe/lit-mobx

If you make a LitElement property be a MobX observable class, you'll get the behavior you want here.

**Comment by septatrix** [comment]
This issue is not about a state management library and I think should there not be closed without proper discussion of potential benefits and drawbacks.

Currently properties need to be registered in the corresponding static function to be watched. The only thing which is watched however, is direct manipulation of the identity because only getters/setters are used. Switching to the Proxy API however would enable to also watch for nested/deep manipulation without any kind of complex state library...

**Comment by justinfagnani** [comment]
Any time you're dealing with reactivity, and especially deep property reactivity, you're dealing with a spectrum of responsibilities that definitely includes state management. The popular state management libraries like Redux and MobX specifically address the problem of listening for updates to state, and triggering code listens for updates.

LitElement wades into this territory with reactive properties, but decidedly stays minimal by only implementing shallow observation of property value changes. This in large part because opinions and needs vary so greatly here that almost nothing we could do by default would satisfy even a majority of users, and because the additional complexity and cost of implementing these solutions goes against the minimist goals of LitElement. We'd much rather allow you to integrate with other solutions so that you can choose what's appropriate for you.

As for Proxies specifically, note that "Proxy" doesn't nearly begin to describe what would be needed for something usable here. First, a Proxy needs to wrap something. Given an uninitialized property we can implement a setter that wraps the value with a Proxy, sure, but what does this get us? We have to ensure that all mutating references to the object are referencing the Proxy and not the underlying object, otherwise we wouldn't be able to observe any changes. That in and of itself is a problem, but it gets much worse.

Then we have to implement a membrane pattern with the Proxy. Any property that's accessed from the Proxy has to return another Proxy. This goes for arrays, Sets, Maps, and method return values too. Membranes for collections have to wrap any method that exposes items, like `get()`, but also `forEach`, `entries()`, and we'd really want to capture `Array.from(collection)` somehow.

Then we have to decide what constitutes a mutation. It's easy enough for simple properties, but how can we tell if a method call mutates state? And which state if we're trying to implement fine-grained change tracking? What if the object has methods that take callbacks and the callback and then mutate state? We have to wrap the methods to wrap the callbacks to wrap to arguments to the callback to track mutations...

What if the objects are DOM Nodes and mutations may come in from a very, very vast API or user inputs like with `contenteditable`? Or the Nodes may be accessed directly via the DOM, thus going around the Proxy/membrane.

There is a lot that could be done, but it's a very fraught area and requires a lot of code to do in a way that's fool-proof enough, and is likely to have high memory and performance overhead. This is one reason Angular goes with an expression dirty-checking approach and zone.js, and one reason React doesn't do any of this at all.

Not to mention that Proxy isn't polyfillable and doesn't work in IE.

So back to MobX. It implements a subset of deep property observation, and that subset is pretty use-case tested at this point. It's well known, well maintained, well documented, completely optional, and has great integration with LitElement. You can implement deeply reactive properties pretty easily:

```ts
import { LitElement, html, TemplateResult, customElement } from 'lit-element';
import { observable, action } from 'mobx';
import { MobxLitElement } from '@adobe/lit-mobx';

class Counter {
    @observable
    count = 0;

    @action
    increment() {
        this.count++;
    }
}

@customElement('my-element')
class MyElement extends MobxLitElement {
    @property({attribute: false})
    counter = new Counter();

    render() {
      return html`
        <button @click=${this.incrementCount}>${this.counter.count}</button>
      `;
    }

    incrementCount() {
        this.counter.increment();
    }
}
```

With this, if you mutate `el.counter.count` it will trigger a render. This is about as close as we would get to deep reactivity if we implemented something ourselves, but... we don't have to! And we leave LitElement lean for those who don't need this, or would rather use Redux or another pattern.

**Comment by septatrix** [comment]
Okay I begin to see your point. However it's actually not too hard to implement nested watchers using Proxies. Please have a look at [`@nx-js/observer-util`](https://github.com/nx-js/observer-util) (or [`@vue/reactivity`](https://github.com/vuejs/vue-next/tree/master/packages/reactivity)).
These libraries support deep reactivity of built-in elements like Objects, Arrays and Maps without too much code.

Supporting other collections like `HTMLCollection` I think does not lie in the scope of this issue as these cases are very rare and generally should be solved using events anyway.

However deep reactivity (of especially Arrays) is very important in my eyes as such use cases are very frequent and lead to a lot of confusion for new users. Therefore it should be batteries included.

**Comment by web-padawan** [comment]
We do need something for arrays, e.g. in the components like `vaadin-grid` where we have `items` property that is used  to render infinite list of rows.

Although we also consider dropping `items` array and only using `dataProvider` property which is a function that lets user to take care of data, and leaves us to handle caching.

**Comment by justinfagnani** [comment]
Arrays are still difficult. Imagine you have some sort of observable array as a property, but a user does this:

```
const myArray = [1, 2, 3];
element.arrayProperty = myArray;
myArray.push(4);
```

There's no reasonable way to observe that change. Even if you wrap the array in a proxy in the setter, the original reference will be to the unobserved, underlying array.

**Comment by web-padawan** [comment]
I see your point about the complexity that this brings. As I mentioned, in Vaadin components we only have `items` property in few components and we will most likely have to rework it.

As a side note, do you think it would make sense to have a mixin that would bring functionality that we had with Polymer for mutating – `notifySplices`, `notifyPath` and their friends?

**Comment by septatrix** [comment]
Yeah such code would be impossible to make reactive. I admit Proxies don't
fix all problems but they are useful nevertheless.

If Proxy based reactivity were to be implemented there could be a section
in the docs stating what they can (nearly everything) and can't do. It's
not like we're losing much just not gaining everything (but that is just
because of ECMAScript)

**Comment by justinfagnani** [comment]
You can absolutely already use one of the Proxy/observable libraries though. Just use `https://github.com/nx-js/observer-util` and call `requestUpdate()` in the observe callback. What else is there to do?

**Comment by septatrix** [comment]
There is nothing more to do. However as Proxies are very lightweight this
should IMHO be included in lit-element by default and I think many people
in the community share this view.

Though as said before Proxies are not supported in IE. Therefore - if the
decision is to leave this issue closed and not implemented it - I think a
fair compromise would be to put this into the backlog for a future version
which drops IE support?

**Comment by dineug** [comment]
hoping to be of help to sb.
Reactive with a simple proxy

example [stackblitz](https://stackblitz.com/edit/lit-observable?file=Observable.ts)
