### ISSUE TITLE
classMap example is a 404

### ISSUE THREAD

**Issue by robdodson** [Polymer/lit-element#813]
#### Steps to Reproduce
1. Go to https://lit-element.polymer-project.org/guide/styles#external-stylesheet
2. Click the "lit-html’s classMap or styleMap directives" link

#### Expected Results
A page with an example of how to use the classMap or styleMap directives with LitElement.

#### Actual Results
404, url is "/TODO"

**Comment by robdodson** [comment]
I guess this is a dupe of #720 which is a dupe of #534.
Would be nice to show how to pull in these directives because I guess [they're no longer part of LitElement](https://github.com/Polymer/lit-element/blob/47e7e88557d7840056a331527f0dadbc2d7a06df/CHANGELOG.md#removed-1)? Do I need a separate import for lit-html?

**Comment by jordanaustin** [comment]
From what I've seen you need to pull in lit-html separately. However this can cause a problem when LitElement depends on a different version of lit-html than the one you pull in for the directives

**Comment by robdodson** [comment]
Thanks @jordanaustin!

> However this can cause a problem when LitElement depends on a different version of lit-html than the one you pull in for the directives

Yeah this seems tricky. Would definitely want the Lit team to offer a recommended best practice here.

**Comment by jordanaustin** [comment]
> Yeah this seems tricky. Would definitely want the Lit team to offer a recommended best practice here.

I agree! It would be nice to use `import { classMap } from 'lit-element/directives/classMap'` or something like that. Of course I get why it's in lit-html, and housing it there makes sense. We need a way to handle this without having to manage keeping your lit-html version to make sure it matches your lit-element's version of lit-html 🤯

**Comment by arthurevans** [comment]
So `lit-html` is already a dependency of `lit-element`, so you _should_ be able to just do:

`import {classMap} from 'lit-html/directives/class-map.js';`

However, at present that doesn't seem to work in our stackblitz samples, which I assume has something to do with how they resolve module names.

When installing other packages that might require lit-html directly, I think the best practice here is to use the loosest version requirements that work for your project (like `^2.0.0` instead of `^2.1.0` (and similarly when authoring packages that depend on `lit-html` alone) so that you maximize the chances of satisfying multiple requirements with the same version. /cc @justinfagnani for more input here.

**Comment by arthurevans** [comment]
Planning on addressing these best practices in an upcoming update on tooling.

**Comment by sorvell** [comment]
Closing since the 404 in the docs page has been fixed. If there's a remaining issue with a specific example, please open a separate issue.
