### ISSUE TITLE
html` ${html`<something property=${object} />`} `

### ISSUE THREAD

**Issue by yorrd** [Polymer/lit-element#82]
When nesting `html`` `-tags, properties get stringified, objects will appear as `[object Object]`

**Comment by jsilvermist** [comment]
Instead of escaping the inner literal, try adding it as:
```js
html`Hello ${html`Meep`}!`;
```

**Comment by yorrd** [comment]
@jsilvermist yes and when I use a function which wraps the html`` call within another one, any object property I use is stringified. If you can't reproduce it, let me know, I'll throw together a reproduction

**Comment by sorvell** [comment]
This definitely unexpected, but we'll need to investigate. A reproduction would be helpful. Thanks!

**Comment by positlabs** [comment]
Here's a repro: https://codepen.io/positlabs/pen/BVpEOj?editors=1000

Is there a recommended way of handling loops within the html template strings? I remember dom-repeat(?) in polymer, but I'd rather not use that.

**Comment by TimvdLippe** [comment]
You should not call join to get a string, but just pass in the array
directly: https://codepen.io/anon/pen/OEWGKX?editors=1000

**Comment by sorvell** [comment]
Here's an example demonstrating that the problem as initially described is working as intended: http://jsbin.com/yoqosif/edit?html,output.

It's unclear based on the latest discussion if there's an actual problem here so closing this issue. Please feel free to open a more specific issue if necessary. Thanks.
