### ISSUE TITLE
CamelCase on EDGE ?

### ISSUE THREAD

**Issue by RoXuS** [Polymer/lit-element#828]
Hi !

We don't have the same behavior on Chrome and Edge (both with last version).

```js
<my-element ?favoriteMode="${favoriteMode}" .otherProperties="${myValue}">
```

Works on Chrome but on edge we have to write:

```js
<my-element ?favoritemode="${favoriteMode}" .otherProperties="${myValue}">
```

Whereas the property works in two cases but not the boolean. Why ?

my-element:
```js
...
static get properties() {
  return {
    favoriteMode: { type: Boolean },
    otherProperties: { type: Object },
  }  
}
...
```

**Comment by CaptainCodeman** [comment]
I'm assuming that it's the attribute not being set that isn't working, personally I'd always set the attribute to something html compatible (case insensitive) which in this case would be `favorite-mode` (I'd probably stick a 'u' in there too because of my UK upbringing).

`favoriteMode: { type: Boolean, reflect: true, attribute: 'favorite-mode' },`

PS: "Camelcase" not being "CamelCase" is  ... argh !! LOL

**Comment by RoXuS** [comment]
Ahah ! Thx @CaptainCodeman with your solution it is ok on the two browsers but it stranges that it is the case only with. the boolean :(

**Comment by LarsDenBakker** [comment]
Html is lowercase, using uppercase in unspecified so it depends on the browser how its handled. By default lit element reads the lowercase property name from attributes.

Prefixing with a . sets a js property, not a html attribute. Thats why it isnt a problem there.

Prefixing with ? Sets a html boolean atrribute. You can just use . there as well if your intention is to set a js property.

**Comment by RoXuS** [comment]
It's super clear @LarsDenBakker, thx !
