### ISSUE TITLE
Hook for Theming

### ISSUE THREAD

**Issue by dfreedm** [Polymer/lit-element#870]
@web-padawan 

In #866, I moved style initialization from `finalize()` to `initialize()` to help implement a theming api for [Material Web Components](https://github.com/material-components/material-components-web-components). However, this API change should also be helpful for Vaadin, and many other theme APIs that might come up.

Let's use this issue to agree on an API contract for theme injection in LitElement.

**Comment by dfreedm** [comment]
My Proposal:

Make a new static method, `getStyles()`, that will be called once per class, at the first instance's `initialize()` time.

Example:
```ts
class LitElement {
  static getStyles() {
    return this.styles || [];
  }
}

class ThemeElement extends LitElement {
  static getStyles() {
    return [...super.getStyles(), ...ThemeManger.get('theme-element')]
  }
}
```

**Comment by justinfagnani** [comment]
cc @aomarks 

@dfreedm is the assumption that any theming system will override a hook (perhaps like `statis getStyles()` we talked about in chat) to provide extra styles from a theme?

If the override is static, this seems like it's fine for global themes, but wouldn't allow for tree-based theming. What are the thoughts there? @aomarks have you done any explorations on that?

**Comment by dfreedm** [comment]
I feel like tree-based theming is best accomplished with CSS Custom Properties, and perhaps with `::part`, when that is mature, or a polyfill is good enough to use.

A user can always turn global theming into tree-based theming by adding CSS Custom Properties via the global system.

**Comment by web-padawan** [comment]
Thanks for prioritizing this. Having a static override would be aligned with `ThemableMixin`.

At this point we are not particularly interested in tree-based theming, and the API convention that we follow internally is to [propagate "theme" attribute](https://github.com/vaadin/vaadin-themable-mixin#theme-attribute-and-subcomponents) to sub-components. So e.g. `vaadin-combo-box` which internally used `vaadin-text-field` propagates the attribute to it.

Another reason why tree-based theming is not quite trivial for us: we have `vaadin-overlay` that teleports its stamped content under `<body>` in order to avoid stacking context trap.
