### ISSUE TITLE
The incorrect Boolean properties conversion

### ISSUE THREAD

**Issue by bogdaniy** [Polymer/lit-element#916]
#### Live Demo
https://jsfiddle.net/kqvwapL1/1/

#### Steps to Reproduce
1. Create an empty lit-element component `my-element`,  with a simple Boolean property
```bool: { type: Boolean, attribute: true, reflect: true }```
2. Use element in the HTML without any attributes ```<my-element />```
3. Log `bool` property value

#### Expected Results
I expect to have a property to be cast in specified Boolean datatype, thus have  `false` value.

For example, raw HTML `<input />` element without `disabled` property in HTML layout, will have it equals `false` in the node instance.

#### Actual Results
The value of the `bool` property is `undefined`

### Browsers Affected
- All of the browsers

### Versions
latest

**Comment by justinfagnani** [comment]
LitElement doesn't assign default values to any properties, regardless of the converter used or the `type` option. Like any other JavaScript class field, that's the responsibility of the class author to do in the constructor.

```js
class MyElement extends LitElement {
  static properties = {
    bool: {type: Boolean, attribute: true, reflect: true}
  };
    
  constructor() {
    this.bool = false;
  }
  // ...
  }
```

**Comment by bogdaniy** [comment]
@justinfagnani thank you for the lightning response, I appreciate that :) Though I do not agree with the fact that `false` is the default value in this case.  HTML spec https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes defines it as:

> The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

Thus the absence of boolean value is considered as a special kind of value, which is different from the other data types, where an absence of value is an absence of value :) So, I'm wondering why such inconsistency with HTML spec was introduced?

**Comment by justinfagnani** [comment]
LitElement is both an HTML element and a JavaScript class. Uninitialized fields in JavaScript are `undefined`. Doing otherwise would introduce an inconsistency with JavaScript. We also don't initialize other types: we don't set strings to `''`, numbers to `0`, etc. Those have less obvious defaults. If we initialized just `Boolean` properties, LitElement would be inconsistent with itself.

Our guiding principle here is that JavaScript already provides a way to initialize fields to default values, and we don't want to re-invent JavaScript features.

**Comment by sorvell** [comment]
Closing based on the explanation above.
