### ISSUE TITLE
Change event not bubbling outside Shadow DOM

### ISSUE THREAD

**Issue by ramoncarreras** [Polymer/lit-element#922]
### Description
`change` event, on input, not bubbling outside shadow dom.

#### Live Demo
https://stackblitz.com/edit/lit-element-example-7p4jwv

#### Steps to Reproduce
Just click at the checkbox and take a look at the browser console.

#### Expected Results
`change` event should bubble, like the rest (`input`, `click`, ...)

#### Actual Results
`change` event is not bubbling outside shadow dom.

### Browsers Affected

- [x] Chrome
- [x] Safari 13
- [ ] Firefox
- [ ] IE 11
- [ ] Edge

### Versions
- lit-element: v2.2.1

**Comment by justinfagnani** [comment]
`change` events are not [composed](https://developer.mozilla.org/en-US/docs/Web/API/Event/composed) so this is expected behavior. If you want to notify elements outside a shadow root of a change inside a shadow root, you should either dispatch a new event, or you could re-dispatch the existing `change` event.

**Comment by plumbblake** [comment]
@justinfagnani Trying to dispatch the existing `change` event gives me an error. 
>Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.

So what would it look like to re-dispatch the existing `change` event?

```
<input @change=${(event) => this.dispatchEvent(event)} type="file" accept=".csv" />
```

**Comment by andyvanee** [comment]
@plumbblake I just came across the same issue and solved the problem of re-dispatching the event based on [this post](https://stackoverflow.com/a/20541207/807865).

The simplest possible translation of your example would look like this:

    <input @change=${(event) => this.dispatchEvent(new event.constructor(event.type, event))} type="file" accept=".csv" />

The problem with this is that `event.target` becomes *your element* rather than the *input element*, and so it may not be useful. To fix this issue, you need to set a property on your element and then dispatch the event. That way you can actually access the value. My solution looks something like this:

```js
class MyElem extends LitElement {
    static get properties() {
        return {
            value: { type: String }
        }
    }
    change(ev) {
        this.value = ev.target.value
        const ev2 = new ev.constructor(ev.type, ev)
        this.dispatchEvent(ev2)
    }
    render() {
        return html`
            <input @change=${ev => this.change(ev)} />
        `
    }
}
```
