### ISSUE TITLE
TypeScript Boolean constructor not working for properties

### ISSUE THREAD

**Issue by DAMEK86** [Polymer/lit-element#948]
I like to override an default boolean property from outside but unfortunately i did the job only done, if i use a custom converter.
For Number and String types the behavior is as expected.

here is an example with the expected behavior with different 
https://stackblitz.com/edit/lit-element-boolean-constructor-not-working

tested browsers under linux

- [x] chrome (Version 80.0.3987.149)
- [x] firefox (Version 74.0)

since lit-element is new for me, i am not sure if it is a typescript or an lit-element problem.

**Comment by abraham** [comment]
Boolean properties are set by the presence of the attribute, not the attribute value.

For the following show is true
```html
<boolean-test show></boolean-test>
<boolean-test show="false"></boolean-test>
```

For the following show is false
```html
<boolean-test></boolean-test>
```

This does however mean that the default value for boolean properties can't be `true` or you can never set it to false with an attribute. So instead of `show` with a default of `true` you would use the opposite with something like `hide` with a default value of `false`.
