### ISSUE TITLE
feature request: one-time / init binding

### ISSUE THREAD

**Issue by amitport** [Polymer/lit-element#950]
## Description
sometimes you need a template for a components that have read-only properties
for example a playing-card component can expect `suit` and `rank` but those are not going to change (maybe other attributes like `selected` is). Checking for changes over and over for those properties is unnecessary computation.

## Acceptance criteria
IMO `PropertyDeclaration` should have an option like `initOnly` that only assign the value in the first time and then avoids checking changes (I'm not really sure, but I think this also affects `lit-html` binding)

**Comment by sorvell** [comment]
There's a long standing issue to support static bindings in lit-html (https://github.com/Polymer/lit-html/issues/78).

We're not inclined to add a specific feature like `initOnly` to LitElement because we're trying to keep the library small and focused, but it should be pretty easy to add yourself in a base class.

Here's an example of how this might be done: https://stackblitz.com/edit/lit-element-init-only-property?file=src%2Fmy-element.js

**Comment by justinfagnani** [comment]
> Checking for changes over and over for those properties is unnecessary computation.

LitElement doesn't actively check for changes to properties. The setters trigger updates on demand if they change. If they don't change, no work is done.

For the bindings in lit-html, checking that the value changed is cheap.
