### ISSUE TITLE
[Typescript] Property value cannot be changed within a decorator

### ISSUE THREAD

**Issue by danipv** [Polymer/lit-element#967]
### Description
Error throwing when a property value is changed within a decorator.

The framework produce the error `Cannot read property 'has' of undefined` on `_requestUpdate` method due to the lack of `_changedProperties` attribute.

However if the property is changed through the 'Click Count' button everything goes right and the value is updated. 

Just to give some additional information that can be useful when the value is changed from the decorator the value of `this` inside the `_requestUpdate` is a `HTMLElement` object, but when the value is changed from the button the value is `<my-element></my-element>`.

This is all the code needed to reproduce the error. I just defined a TS decorator as described here: https://www.typescriptlang.org/docs/handbook/decorators.html and I use it over a property already decorated with `@property`.
```
import {LitElement, html, customElement, property} from 'lit-element';

function decorator() {
  return (target: any, name: string) => {
    setTimeout(() => {
      target[name] = 10; // count
    }, 1000);
  };
}

@customElement('my-element')
export class MyElement extends LitElement {
  @decorator()
  @property({type: Number})
  count = 0;

  render() {
    return html`
      <button @click=${this._onClick} part="button">
        Click Count: ${this.count}
      </button>
    `;
  }

  private _onClick() {
    this.count++;
  }
}
``` 
#### Live Demo
https://stackblitz.com/edit/lit-element-properties-problem-pty4zj?file=my-element.ts

#### Repo Demo
https://github.com/danipv/lit-element-custom-decorator-test

#### Steps to Reproduce
1 - Create a basic typescript decorator as described above and use it over a class property.
2 - Change the property value within the decorator.

#### Expected Results
The value of the property decorated is updated without errors.

#### Actual Results
The value change produce the error `Cannot read property 'has' of undefined` when lit performs the update.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Versions
- lit-element: v2.3.1
- webcomponents: v2.4.0

**Comment by sorvell** [comment]
Customizing a property like this is better done by overriding the `getPropertyDescriptor` method. This is used to create the property accessor for any property decorated with `@property`.

That said, composition of decorators like this is a bit tricky and since the spec and feature is evolving there are some rough edges.  In general the `target` you get in the decorator is the object's prototype and therefore setting a value directly is likely not what you want to do.

Typically an accessor decorator returns a property descriptor and you can achieve what you're going for by implementing a getter/setter. However, our `@property` directive cannot simply return a property descriptor and therefore you'd have to look up the existing descriptor yourself. Here's a quick example, hope it helps:

https://stackblitz.com/edit/lit-element-properties-problem-sfctxj?file=my-element.ts

**Comment by Aruinerk** [comment]
I just got a similar problem while calling a method of my LitElement instance by  a event-listener.

Demo: https://stackblitz.com/edit/lit-element-properties-has-undefined?file=my-element.ts
