### ISSUE TITLE
IE11 support 

### ISSUE THREAD

**Issue by v1r** [Polymer/lit-element#98]
Hi there,

 I was just wondering if Polymer 3 will work in IE11? 
because JS imports won't work... is there any polyfill for that? 
https://caniuse.com/#feat=es6-module

**Comment by Lodin** [comment]
Well... [Webpack](https://webpack.js.org/)?

**Comment by TimvdLippe** [comment]
You can bundle the imports away during building with `polymer build`: https://github.com/Polymer/tools/tree/master/packages/build#bundling-files You can use the `es5-bundled` preset from the CLI: https://www.polymer-project.org/3.0/docs/tools/polymer-json#inherit as well as transform your ES modules to AMD modules with https://www.polymer-project.org/3.0/toolbox/build-for-production#amd

**Comment by v1r** [comment]
Thanks!

**Comment by mikeaustin** [comment]
@TimvdLippe My company is also looking for IE 11 support. I get the gist of what you're talking about with polymer-build, but it would be very helpful if there was a preconfigured base project instead of learning polymer-build, installing CustomElementsEs5Adapter, the polyfills, etc. and hoping it works. I want to use lit-element for a new project, but it would expand the timeline to support IE 11.

**Comment by johnthad** [comment]
@mikeaustin You might want to look at https://open-wc.org/. I was able to get `pwa-starter-kit` built using `open-wc` recommendations, and it ran on IE11. I think the `books` demo would work, too, just adding a `fetch` polyfill. The `open-wc` folks are on the Polymer Slack channel, and have been _very_ helpful.

**Comment by mikeaustin** [comment]
Thanks for the quick reply @johnthad. I bumped into open-wc earlier today and finally got it working in IE 11. One thing though, it splits the module into two separate builds. Not bad for an app, but a little bulky for many small components. I really with I could ditch IE 11, and I stated my case, but alas, we need to support it. The route we’re taking is to be compatible with web components in a React app, but we won’t use/create them until dropping IE 11. For personal project, I will start using lit-element. I like how minimal it is, using JS template literals instead of a compiler (Babel/JSX). We’re almost free from even webpack!
