### ISSUE TITLE
Type definitions of LitElement

### ISSUE THREAD

**Issue by timonson** [Polymer/lit-element#991]
I am searching and looking for ways to generate the type definitions of `LitElement`. They don't seem to be in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#readme) and I could not generate them myself after cloning this repo.

The reason I am asking is that I wanna use lit-element without downloading it via npm.

At the moment I do the following which works nicely with the exception of not having the `LitElement` types and the types of its methods of course.

```typescript
import {
  LitElement,
  html,
  css,
  unsafeCSS,
  customElement,
  property,
  // @ts-ignore
} from "https://unpkg.com/lit-element/lit-element.js?module"

@customElement("my-greeter")
export class MyGreeter extends (LitElement as any) {
  @property() topic = "Website"
  @property() mood = "awesome"
  @property({ attribute: "theme-color" }) themeColor = ""
  attributeChangedCallback(
    name: string,
    oldValue: string | null,
    newValue: string | null
  ) {
    super.attributeChangedCallback(name, oldValue, newValue)
    if (newValue === oldValue) return
    switch (name) {
      case "theme-color":
        this.style.setProperty("--themeColor", newValue)
        break
      default:
    }
  }

  static get styles() {
    return css`
      :host {
        display: block;
        text-align: center;
        --themeColor: pink;
      }
      .colorful {
        color: var(--themeColor);
      }
      .decorated {
        text-decoration: var(--themeColor) double underline 2px;
      }
    `
  }

  render() {
    return html`<h1>
      Our <span class="decorated">${this.topic}</span> is
      <span class="colorful">${this.mood}</span>!
    </h1>`
  }
}
```

With this procedure, all I need to do is compiling the code with `tsc`. I don't need to download npm or `lit-element`. Like I said, all what needs to be done is replacing `as any` with the right type of `LitElement`

Thank you!

**Comment by justinfagnani** [comment]
LitElement is written in TypeScript and we publish the type declarations with the npm package.

We only support installing the package via npm. unpkg.com just serves the files from the npm package, so in a sense you are using npm when you use unpkg.com,a dnthe types are already [there](https://unpkg.com/lit-element@2.3.1/lit-element.d.ts).

However, this isn't a supported configuration by TypeScript, so the question here is more of a TypeScript compiler question: can you get it to load types from a URL?

I'm not sure what utility you're getting from running a local build, but _not_ installing the dependencies locally. I would take a hard look at whether that approach is worth the extra effort required to be off the well-lit path.

I'm going to close this, since it's not really a LitElement issue and not a supported configuration, so there's nothing for us to do here, but feel free to continue the conversation.

**Comment by timonson** [comment]
Thank you very much @justinfagnani !

**Comment by abraham** [comment]
TypeScript does support importing types directly. I'm not sure if it'll work from a URL but you could try something like this:

```ts
export class MyGreeter extends (
  LitElement as import("https://unpkg.com/lit-element/lit-element.d.ts?module").LitElement
) {}
```

**Comment by timonson** [comment]
@justinfagnani  and @abraham: You can't import TS from a URL yet and I knew this. But I also tried to import the locally saved lit-element.d.ts file but tsc throws errors there as well, what doesn't seem to be optimal.

**Comment by miltonhowe** [comment]
@timonson Did you find a way to make this work?
I want to do the same thing. I want to add Lit to an existing ASP.NET MVC project which of course uses MSBuild to manage NuGet packages and tsc, all without using npm. Adding new steps to the build chain faces pushback from the rest of the team so I would prefer a seamless integration.

**Comment by timonson** [comment]
Hi @miltonhowe , I would recommend using deno for this job.

You can install deno with one command from its [homepage](https://deno.land/) and run the following command to bundle the library: deno bundle https://esm.sh/lit-element

You can find more information [here](https://deno.land/manual@v1.15.2/npm_nodejs/cdns).

If you wonder what [esm.sh](https://esm.sh/#docs) is: It is a CDN for node packages for deno.

I hope this helps!

**Comment by miltonhowe** [comment]
Thank you @timonson , I found what I consider a decent workaround where i am able to load the modules from CDN without any bundling, node, node_modules, npm, nothing. I am using importmaps plus a shim for older browsers.
```
<script async src="https://ga.jspm.io/npm:es-module-shims@1.6.3/dist/es-module-shims.js"></script>
<script type="importmap">
{
  "imports": {
    "lit": "https://unpkg.com/lit/index.js",
    "lit/": "https://unpkg.com/lit/",
    "lit-html": "https://unpkg.com/lit-html/lit-html.js",
    "lit-html/": "https://unpkg.com/lit-html/",
    "lit-element": "https://unpkg.com/lit-element/lit-element.js",
    "lit-element/": "https://unpkg.com/lit-element/",
    "@("@")lit/": "https://unpkg.com/@("@")lit/",
    "@("@")lit/reactive-element": "https://unpkg.com/@("@")lit/reactive-element/reactive-element.js"
  }
}
</script>
```

in my components I use bare imports like I was in an Angular app, but it is vanilla JS with no webpack or any kind of bundler.
I used trial and error and just kept adding each reference until I had added them all. The weird syntax with the @ signs is because this is in an ASP.NET MVC razor template which uses the @ sign for the helpers.

I actually first got this importmap thing working with local files in node_modules but once I realised that it worked and I could load from unpkg I decided to remove npm from the build process since I only needed it for Lit. The Typescript compilation is handled by Nuget package `Microsoft.TypeScript.MSBuild`.
